#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef REALSDK_SWIFT_H
#define REALSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RealSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC7RealSDK10AlarmClock")
@interface AlarmClock : NSObject
@property (nonatomic) NSInteger clockType;
@property (nonatomic) NSInteger timeStamp;
@property (nonatomic) BOOL isOn;
@property (nonatomic) NSInteger weekday;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK16AppleNotifyModel")
@interface AppleNotifyModel : NSObject
@property (nonatomic) BOOL isCall;
@property (nonatomic) BOOL isMessage;
@property (nonatomic) BOOL isWechat;
@property (nonatomic) BOOL isQQ;
@property (nonatomic) BOOL isFacebookMessage;
@property (nonatomic) BOOL isSkype;
@property (nonatomic) BOOL isTwitter;
@property (nonatomic) BOOL isWhatapp;
@property (nonatomic) BOOL isInstagram;
@property (nonatomic) BOOL isSnapchat;
@property (nonatomic) BOOL isFacebook;
@property (nonatomic) BOOL isLinkedin;
@property (nonatomic) BOOL isLine;
@property (nonatomic) BOOL isGmail;
@property (nonatomic) BOOL isVK;
@property (nonatomic) BOOL isTelegram;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class NSDate;

SWIFT_CLASS("_TtC7RealSDK16AutoMeasureModel")
@interface AutoMeasureModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull mac;
@property (nonatomic) NSInteger weekday;
@property (nonatomic) BOOL isOn;
@property (nonatomic, copy) NSDate * _Nonnull startTime;
@property (nonatomic, copy) NSDate * _Nonnull endTime;
/// 分钟
@property (nonatomic) NSInteger interval;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7RealSDK11BatteryInfo")
@interface BatteryInfo : NSObject
/// 电量
@property (nonatomic) NSInteger value;
/// 是否在充电
@property (nonatomic) BOOL isCharge;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK9DataModel")
@interface DataModel : NSObject <NSCopying>
@property (nonatomic, copy) NSString * _Nonnull uuidString;
@property (nonatomic, copy) NSString * _Nonnull mac;
@property (nonatomic) NSInteger timeStamp;
@property (nonatomic, copy) NSString * _Nonnull dateStr;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7RealSDK10BloodModel")
@interface BloodModel : DataModel
/// 血压高值
@property (nonatomic) NSInteger max;
/// 血压低值
@property (nonatomic) NSInteger min;
@property (nonatomic) NSInteger type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC7RealSDK19DeviceReminderModel")
@interface DeviceReminderModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull mac;
@property (nonatomic) NSInteger weekday;
@property (nonatomic) BOOL isOn;
@property (nonatomic, copy) NSDate * _Nonnull startTime;
@property (nonatomic, copy) NSDate * _Nonnull endTime;
/// 分钟
@property (nonatomic) NSInteger interval;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC7RealSDK10HeartModel")
@interface HeartModel : DataModel
/// 心率值
@property (nonatomic) NSInteger heart;
@property (nonatomic) NSInteger heart1;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK9HuXiModel")
@interface HuXiModel : DataModel
/// a)01 呼吸
/// b)02 压力
/// c)03 体温
/// d)04 血糖
@property (nonatomic) NSInteger type;
/// 兼容体温取真实值 * 10
@property (nonatomic) NSInteger oxygen;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK16JLCentralManager")
@interface JLCentralManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK12LongSitModel")
@interface LongSitModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull mac;
@property (nonatomic) NSInteger weekday;
@property (nonatomic) BOOL isOn;
@property (nonatomic, copy) NSDate * _Nonnull startTime;
@property (nonatomic, copy) NSDate * _Nonnull endTime;
/// 分钟
@property (nonatomic) NSInteger interval;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7RealSDK12MDBleManager")
@interface MDBleManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK11MDDataModel")
@interface MDDataModel : DataModel
/// a)01 呼吸
/// b)02 压力
/// c)03 体温
/// d)04 血糖
@property (nonatomic) NSInteger dataType;
/// 兼容体温取真实值 * 10
@property (nonatomic) NSInteger numValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK11MDFuncModel")
@interface MDFuncModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end







/// 勿扰模式
SWIFT_CLASS("_TtC7RealSDK14NoDisturbModel")
@interface NoDisturbModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull mac;
@property (nonatomic) BOOL isOn;
@property (nonatomic, copy) NSDate * _Nonnull startTime;
@property (nonatomic, copy) NSDate * _Nonnull endTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7RealSDK11OxygenModel")
@interface OxygenModel : DataModel
/// 血氧
@property (nonatomic) NSInteger oxygen;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK7RealDog")
@interface RealDog : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 抬手亮屏设置
SWIFT_CLASS("_TtC7RealSDK21ScreenTimePeriodModel")
@interface ScreenTimePeriodModel : NSObject
@property (nonatomic) NSInteger weekday;
@property (nonatomic) BOOL isOn;
@property (nonatomic, copy) NSDate * _Nonnull startTime;
@property (nonatomic, copy) NSDate * _Nonnull endTime;
/// 亮度等级
@property (nonatomic) NSInteger lightLevel;
/// （以秒为单位）最少5s起
@property (nonatomic) NSInteger lightDuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7RealSDK9SleepInfo")
@interface SleepInfo : DataModel
/// 睡眠数据 单位 分钟
/// Sleep data Unit minutes
@property (nonatomic) NSInteger sleep;
@property (nonatomic) NSInteger deep;
@property (nonatomic) NSInteger light;
@property (nonatomic) NSInteger wakeup;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK10SleepModel")
@interface SleepModel : DataModel
/// 0, 1, 2 对应清醒，浅睡，深睡
@property (nonatomic) NSInteger state;
/// 睡眠时间 单位 分钟
@property (nonatomic) NSInteger sleepTime;
@property (nonatomic) NSInteger hour;
@property (nonatomic) NSInteger min;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK10SportModel")
@interface SportModel : DataModel
@property (nonatomic) NSInteger step;
@property (nonatomic) NSInteger distance;
@property (nonatomic) NSInteger cal;
/// 运动类型（0室外步行，1室内步行，2室外跑步，3室内跑步，其他待定）
/// （0室外步行，1室内步行，2室外跑步，3室内跑步，4 爬山，5 跳神，6 羽毛球，7 足球，8 篮球，9 户外骑行，10 滑冰，11 健身房，12 瑜伽，13 网球，14 乒乓球，15 游泳，16 性爱，17 健身单车，18 自由训练，19 远足， 20 平板支撑，21 划船机，22 排球，23 棒球，24 跑步机，25 椭圆机，26 举重， 其他
@property (nonatomic) NSInteger sportMode;
@property (nonatomic) NSInteger duration;
@property (nonatomic) BOOL hasGPS;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK8StepInfo")
@interface StepInfo : DataModel
/// 计步数据
/// Step count data
@property (nonatomic) NSInteger step;
@property (nonatomic) NSInteger cal;
@property (nonatomic) NSInteger distance;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK9StepModel")
@interface StepModel : DataModel
@property (nonatomic) NSInteger step;
@property (nonatomic) NSInteger distance;
@property (nonatomic) NSInteger cal;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK10TiWenModel")
@interface TiWenModel : DataModel
/// a)01 呼吸
/// b)02 压力
/// c)03 体温
/// d)04 血糖
@property (nonatomic) NSInteger type;
/// 体温
@property (nonatomic) double tiWenValue;
/// 体温最小值
@property (nonatomic) double xtMinValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end









@class UIImage;

@interface UIScrollView (SWIFT_EXTENSION(RealSDK))
/// 截长屏Image
@property (nonatomic, readonly, strong) UIImage * _Nullable wu_snapshotImage;
@end




@interface UIView (SWIFT_EXTENSION(RealSDK))
/// @objc can override
@property (nonatomic, readonly, strong) UIImage * _Nullable wu_snapshotImage;
- (void)wu_addCommonCorners:(CGFloat)cornerRadius;
@end


@interface UIView (SWIFT_EXTENSION(RealSDK))
/// X Axis value of UIView.
@property (nonatomic) CGFloat x;
/// Y Axis value of UIView.
@property (nonatomic) CGFloat y;
/// Width of view.
@property (nonatomic) CGFloat width;
/// Height of view.
@property (nonatomic) CGFloat height;
/// View’s Origin point.
@property (nonatomic) CGPoint origin;
/// View’s size.
@property (nonatomic) CGSize size;
/// View’s right side (x + width).
@property (nonatomic) CGFloat right;
/// View’s bottom (y + height).
@property (nonatomic) CGFloat bottom;
/// View’s top (y).
@property (nonatomic) CGFloat top;
/// View’s left side (x).
@property (nonatomic) CGFloat left;
/// View’s center X value (center.x).
@property (nonatomic) CGFloat centerX;
/// View’s center Y value (center.y).
@property (nonatomic) CGFloat centerY;
/// Last subview on X Axis.
@property (nonatomic, readonly, strong) UIView * _Nullable lastSubviewOnX;
/// Last subview on Y Axis.
@property (nonatomic, readonly, strong) UIView * _Nullable lastSubviewOnY;
/// X value of bounds (bounds.origin.x).
@property (nonatomic) CGFloat boundsX;
/// Y value of bounds (bounds.origin.y).
@property (nonatomic) CGFloat boundsY;
/// Width of bounds (bounds.size.width).
@property (nonatomic) CGFloat boundsWidth;
/// Height of bounds (bounds.size.height).
@property (nonatomic) CGFloat boundsHeight;
/// Center view to it’s parent view.
- (void)centerToParent;
@end


SWIFT_CLASS("_TtC7RealSDK8UserInfo")
@interface UserInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WUCentralManager;
@class WUBleModel;

SWIFT_CLASS("_TtC7RealSDK12WUBleManager")
@interface WUBleManager : NSObject
@property (nonatomic, strong) WUCentralManager * _Nonnull bleManager;
@property (nonatomic, strong) WUBleModel * _Nonnull bleModel;
@property (nonatomic, copy) NSArray<WUBleModel *> * _Nonnull bleModels;
@property (nonatomic) BOOL isEnterOTA;
@property (nonatomic) BOOL isDspOTA;
@property (nonatomic, readonly) BOOL isConnected;
@property (nonatomic, strong) BatteryInfo * _Nonnull batteryInfo;
@property (nonatomic, strong) StepInfo * _Nonnull stepInfo;
@property (nonatomic, strong) SleepInfo * _Nonnull sleepInfo;
@property (nonatomic, strong) UserInfo * _Nonnull userInfo;
@property (nonatomic, strong) AppleNotifyModel * _Nonnull notifyModel;
@property (nonatomic, strong) LongSitModel * _Nonnull longSitModel;
@property (nonatomic, strong) NoDisturbModel * _Nonnull noDisturbModel;
@property (nonatomic, strong) ScreenTimePeriodModel * _Nonnull screenTimeModel;
@property (nonatomic, strong) AutoMeasureModel * _Nonnull autoMeasureModel;
- (void)reConnectDevice;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC7RealSDK22WUBleManagerNotifyKeys")
@interface WUBleManagerNotifyKeys : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull xinlv;)
+ (NSNotificationName _Nonnull)xinlv SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull xueya;)
+ (NSNotificationName _Nonnull)xueya SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull xueyang;)
+ (NSNotificationName _Nonnull)xueyang SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull huxi;)
+ (NSNotificationName _Nonnull)huxi SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull yali;)
+ (NSNotificationName _Nonnull)yali SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull step;)
+ (NSNotificationName _Nonnull)step SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull off;)
+ (NSNotificationName _Nonnull)off SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull on;)
+ (NSNotificationName _Nonnull)on SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull scan;)
+ (NSNotificationName _Nonnull)scan SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull connected;)
+ (NSNotificationName _Nonnull)connected SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull disconnected;)
+ (NSNotificationName _Nonnull)disconnected SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull stateChanged;)
+ (NSNotificationName _Nonnull)stateChanged SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull batteryLevel;)
+ (NSNotificationName _Nonnull)batteryLevel SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull deviceInfo;)
+ (NSNotificationName _Nonnull)deviceInfo SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull sleep;)
+ (NSNotificationName _Nonnull)sleep SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull sportDayData;)
+ (NSNotificationName _Nonnull)sportDayData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull sportHistoryData;)
+ (NSNotificationName _Nonnull)sportHistoryData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull readyToWrite;)
+ (NSNotificationName _Nonnull)readyToWrite SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull getECG;)
+ (NSNotificationName _Nonnull)getECG SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull startECG;)
+ (NSNotificationName _Nonnull)startECG SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull stopECG;)
+ (NSNotificationName _Nonnull)stopECG SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull jlOTAUpgrade;)
+ (NSNotificationName _Nonnull)jlOTAUpgrade SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull homejlOTAUpgrade;)
+ (NSNotificationName _Nonnull)homejlOTAUpgrade SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull xieTangUpdata;)
+ (NSNotificationName _Nonnull)xieTangUpdata SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull tiwenUpdata;)
+ (NSNotificationName _Nonnull)tiwenUpdata SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull deviceSentorData;)
+ (NSNotificationName _Nonnull)deviceSentorData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull deviceList;)
+ (NSNotificationName _Nonnull)deviceList SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull datacurrent;)
+ (NSNotificationName _Nonnull)datacurrent SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK10WUBleModel")
@interface WUBleModel : NSObject
@property (nonatomic) BOOL isHasMusic;
@property (nonatomic) BOOL isHasYunDong;
@property (nonatomic) BOOL isHasShuiMian;
@property (nonatomic) BOOL isHasXueYa;
@property (nonatomic) BOOL isHasXinLv;
@property (nonatomic) BOOL isHasXueYang;
@property (nonatomic) BOOL isHasYouXi;
@property (nonatomic) BOOL isHasDianZiShu;
@property (nonatomic) BOOL isHasLuYin;
@property (nonatomic) BOOL isHasXiangCe;
@property (nonatomic) BOOL isHasKaBao;
@property (nonatomic) BOOL isHasMingPian;
@property (nonatomic) BOOL isHasQianBao;
@property (nonatomic) BOOL isHasShenli;
@property (nonatomic) BOOL isHasXueTang;
@property (nonatomic) BOOL isHasYali;
@property (nonatomic) BOOL isHasHuXi;
@property (nonatomic) BOOL isHasXinDian;
@property (nonatomic) BOOL isHasTiWen;
@property (nonatomic) BOOL isSendScreenSet;
@property (nonatomic) BOOL ismNeedPaired;
@property (nonatomic) BOOL isBind;
@property (nonatomic, copy) NSString * _Nonnull uuidString;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger rssi;
@property (nonatomic, copy) NSString * _Nonnull mac;
@property (nonatomic) NSInteger deviceVersion;
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic) BOOL isFirstConnected;
@property (nonatomic, copy) NSString * _Nonnull chip;
@property (nonatomic, copy) NSString * _Nonnull macAdvertisementData;
@property (nonatomic) NSInteger screenType;
@property (nonatomic) NSInteger type;
@property (nonatomic) NSInteger width;
@property (nonatomic) NSInteger height;
@property (nonatomic) NSInteger selectTop;
@property (nonatomic) NSInteger selectBottom;
@property (nonatomic) NSInteger red;
@property (nonatomic) NSInteger green;
@property (nonatomic) NSInteger blue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CBCentralManager;
@class CBPeripheral;
@class NSNumber;
@class CBService;
@class CBCharacteristic;

SWIFT_CLASS("_TtC7RealSDK16WUCentralManager")
@interface WUCentralManager : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate>
@property (nonatomic, strong) JLCentralManager * _Nullable jlCentralManager;
@property (nonatomic, copy) NSString * _Nonnull jlLastBleMacAddress;
@property (nonatomic, copy) NSString * _Nonnull savedDeviceIdentifier;
- (void)startFindBleDevices;
- (void)stopFindBleDevices;
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData RSSI:(NSNumber * _Nonnull)RSSI;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface WUCentralManager (SWIFT_EXTENSION(RealSDK))
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end


@interface WUCentralManager (SWIFT_EXTENSION(RealSDK))
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheralIsReadyToSendWriteWithoutResponse:(CBPeripheral * _Nonnull)peripheral;
- (void)peripheralDidUpdateName:(CBPeripheral * _Nonnull)peripheral;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didModifyServices:(NSArray<CBService *> * _Nonnull)invalidatedServices;
@end

@class NSData;

SWIFT_CLASS("_TtC7RealSDK11WUSendModel")
@interface WUSendModel : NSObject
@property (nonatomic) uint8_t head;
@property (nonatomic) uint8_t delegateVersion;
@property (nonatomic) uint8_t keyVersion;
@property (nonatomic) BOOL isSender;
@property (nonatomic) BOOL isSuccess;
@property (nonatomic) NSInteger length;
@property (nonatomic) uint8_t command;
@property (nonatomic) uint8_t key;
@property (nonatomic) uint8_t keyFunc;
@property (nonatomic, copy) NSData * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK12WeatherModel")
@interface WeatherModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RealSDK12XueTangModel")
@interface XueTangModel : DataModel
/// a)01 呼吸
/// b)02 压力
/// c)03 体温
/// d)04 血糖
@property (nonatomic) NSInteger type;
/// 血糖值
@property (nonatomic) double xtValue;
/// 血糖最小值
@property (nonatomic) double xtMinValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
