export default {
	'zh-CN': {
		刷新中: '刷新中。。。',
		刷新失败: '刷新失败',
		注销成功: '注销成功',
		注销失败: '注销失败',
		标准蓝牙提示1: '请在正常使用前，反复按血压计的中间键直到屏幕关闭，退出配对模式',
		您的帐户有绑定: '您的帐户有绑定的设备或和他人共享数据，请先解除绑定和取消共享后再取消帐户',
		手表如何监测睡眠情况: '手表如何监测睡眠情况',
		连接失败: '连接失败，再此点击您的设备型号进行连接\n如果多次不成功，请把设备电源关开，按照上一页的指令再此进入配对模式，再点击设备型号',
		没找到指定设备: '没找到指定设备/设备已被连接',
		请点击重试: '请点击重试，若还是无法连接请app从手机后台清除后重新打开appp绑定',
		此设备已被其他账号绑定: '此设备已被其他账号绑定',
		血压计说明书: '血压计说明书',
		手表说明书: '手表说明书',
		调整表带松紧度的简单方法: '调整表带松紧度的简单方法',
		如何把表带末端的扣取出和放入: '如何把表带末端的扣取出和放入',
		如何在手表关闭经典蓝牙: '如何在手表关闭经典蓝牙',
		如何用手表上打电话: '如何用手表上打电话',
		如何在血压计上切换用户: '如何在血压计上切换用户',
		如何查看血压计的历史数据: '如何查看血压计的历史数据',
		请求失败: '请求失败',
		解绑失败: '解绑失败',
		设备已解绑: '设备已解绑',
		臂式血压计的安装: '臂式血压计的安装',
		臂式血压计的测试方法: '臂式血压计的测试方法',
		设置臂式血压计的方法: '设置臂式血压计的方法',
		臂式血压计如何和手机APP配对: '臂式血压计如何和手机APP配对',
		血压计手表测量血压的方法: '血压计手表测量血压的方法',
		恢复血压计手表出厂设置: '恢复血压计手表出厂设置',
		血压计手表如何和手机APP配对: '血压计手表如何和手机APP配对',
		如何在血压计手表上设置自动血压测试: '如何在血压计手表上设置自动血压测试',
		如何在血压计手表主页上加应用: '如何在血压计手表主页上加应用',
		如何设置血压计手表的语言: '如何设置血压计手表的语言',
		用血压计手表测血压前要检测的两个要点: '用血压计手表测血压前要检测的两个要点',
		如何和其他用户共享数据和设置远程警告: '如何和其他用户共享数据和设置远程警告',
		稍候去设置: '稍候去设置',
		标准蓝牙提示: '注意： 若要接收电话和信息，请在下一个对话框中选择“配对”以启用经典蓝牙。请注意，使用经典蓝牙可能会显著缩短电池使用时间。如果选择“取消”，则会使用低功耗蓝牙，能够延长电池续航时间。低功耗蓝牙仍然可以将数据传输到应用程序，但无法接收电话和信息。\n在配对过程中，手表可能会自动启用经典蓝牙。配对完成后，请务必在手表上手动关闭经典蓝牙，以确保设备处于低功耗模式。有关关闭经典蓝牙的详细操作步骤，请参考帮助中心的使用指南。',
		获取相机权限成功: '获取相机权限成功',
		扫码需要相机权限: '扫码需要相机权限，否则无法扫码',
		您好: '您好',
		欢迎来到JakobLife: '欢迎来到JakobLife',
		请输入会员名或绑定的手机号: '请输入会员名或绑定的手机号/邮箱',
		请输入绑定的手机号或绑定的邮箱: '请输入绑定的手机号/邮箱',
		请输入密码: '请输入密码',
		忘记密码: '忘记密码',
		验证码登录: '验证码登录',
		密码登录: '密码登录',
		获取验证码: '获取验证码',
		已阅读并同意: '已阅读并同意',
		JakobLife软件服务使用协议: '《JakobLife软件服务使用协议》',
		请输入验证码: '请输入验证码',
		登录: '登录',
		还没有JakobLife账号: "还没有JakobLife账号?",
		新用户去注册: '新用户去注册',
		其它登录方式: '其它登录方式',
		添加数据卡片: '添加数据卡片',
		拖动可调整数据卡片位置: '拖动可调整数据卡片位置',
		信息补充: '信息补充',
		相关信息: '请确认以下相关信息，以确保动态血压监测报告的准确性和完整性。',
		报告日期: '报告日期',
		起床时间: '起床时间',
		就寝时间: '就寝时间',
		是否午休: '是否午休',
		午休时长: '午休时长',
		是否服用药物: '是否服用药物',
		当前用药: '当前用药',
		工作是否倒班: '工作是否倒班',
		跳过: '跳过',
		确认: '确认',
		是: '是',
		否: '否',
		动态血压监测报告: '动态血压监测报告',
		动态血压监测报告预览: '动态血压监测报告预览',
		姓名: '姓名',
		性别: '性别',
		年龄: '年龄',
		最新体重: '最新体重',
		初始体重: '初始体重',
		目标体重: '目标体重',
		BMI分类: 'BMI分类',
		根据世界卫生组织的最新BMI分类: '根据世界卫生组织(WHO)的最新BMI分类',
		BMI范围: 'BMI范围',
		分类: '分类',
		体重过轻: '体重过轻',
		正常体重: '正常体重',
		超重: '超重',
		一级肥胖: '一级肥胖',
		二级肥胖: '二级肥胖',
		三级肥胖或病态肥胖: '三级肥胖或病态肥胖',
		血氧分类: '血氧分类',
		偏低: '偏低',
		正常: '正常',
		偏高: '偏高',
		平均: '平均',
		最高: '最高',
		平均收缩压: '平均收缩压',
		平均舒张压: '平均舒张压',
		最近血压: '最近血压',
		收缩压: '收缩压',
		舒张压: '舒张压',
		脉搏: '脉搏',
		平均血压: '平均血压',
		最高血压: '最高血压',
		最低血压: '最低血压',
		血氧: '血氧',
		骨含量: '骨含量',
		肌肉量: '肌肉量',
		蛋白率: '蛋白率',
		水分: '水分',
		内脏脂肪指数: '内脏脂肪指数',
		脂肪率: '脂肪率',
		基础代谢率: '基础代谢率',
		皮下脂肪率: '皮下脂肪率',
		身体年龄: '身体年龄',
		岁: '岁',
		手表: '手表',
		身高: '身高',
		体重: '体重',
		步数: '步数',
		计步: '计步',
		正常血压: '正常血压',
		正常高血压值: '正常高血压值',
		一级高血压: '一级高血压',
		二级高血压: '二级高血压',
		未知: '未知',
		血氧1: '1.检测注意：情绪激动、憋气或检测中的不规范处理均可能会导致动脉血氧饱和度结果不准确',
		血氧2: '2.偏高提示：动脉血氧饱和度>98%，提示若当机体摄入氧浓度过高，一般没有临床意义。在接受高浓度吸氧、高压氧治疗的人群，动脉血氧饱和度可接近100%。',
		血氧3: '3.偏低提示：动脉血氧饱和度<90%，需考虑机体存在缺氧的可能，提示机体存在低氧血症。',
		选择管理1: '请选择一项您主要想管理的内容',
		选择管理2: '之后您可以随时切换主要管理项目',
		选择管理3: '选择要显示的测量值',
		血压管理: '血压管理',
		切换: '切换',
		体脂管理: '体脂管理',
		当前未绑定任何设备: '当前未绑定任何设备',
		此账号还未绑定血压计设备: '此账号还未绑定血压计设备',
		此账号还未绑定体脂秤设备: '此账号还未绑定体脂秤设备',
		最近7天平均体重: '最近7天平均体重',
		变化速度: '变化速度kg/周',
		今日体重: '今日体重',
		最高体重: '最高体重',
		最低体重: '最低体重',
		平均体重: '平均体重',
		历史记录: '历史记录',
		血压: '血压',
		血压计: "血压计",
		心电: '心电',
		体脂: '体脂',
		血糖: '血糖',
		日历: '日历',
		列表: '列表',
		帮助: '帮助',
		回到今天: '回到今天',
		今: '今',
		周一: '周一',
		周二: '周二',
		周三: '周三',
		周四: '周四',
		周五: '周五',
		周六: '周六',
		周日: '周日',
		导出: '导出',
		导出设置: '导出设置',
		导出格式: '导出格式',
		测量时间: '测量时间',
		注1: '注：每次导出时间不能超过一年',
		开始日期: '开始日期',
		结束日期: '结束日期',
		仅导出测量数据: '仅导出测量数据',
		生成动态血压监测报告: '生成动态血压监测报告',
		注2: '注：动态血压监测报告仅支持导出单日数据，需选择相同的开始和结束日期。',
		消息: '消息',
		清除: '清除',
		邀请: '邀请',
		想与您共享健康数据: '想与您共享健康数据',
		共享列表: '共享列表',
		共享给: '共享给',
		与他人共享: '与他人共享',
		设备管理: '设备管理',
		同意: '同意',
		服务协议: '服务协议',
		绑定设备: '绑定设备',
		确认绑定: '确认绑定',
		暂不绑定: '暂不绑定',
		绑定提醒1: '1、将SIM卡按照标识正确插入设备中；',
		绑定提醒2: '2、使用“JakobLife”APP扫描机身标贴的IMEI码或包装彩盒标贴的二维码进行绑定。',
		绑定提醒3: '使用“JakobLife”APP扫描机身标贴的SN码或包装彩盒标贴的二维码进行绑定。',
		打开: '打开',
		关闭: '关闭',
		将血压计开机: '1、将血压计开机',
		设备配对说明: '设备配对说明',
		设备上电: "1. 上电",
		打开设备: '打开设备。',
		准备配对: '2. 进入配对模式',
		确保设备靠近你的手机: '按右建把LCD 打开，然后同时按住左右键，直到屏幕上出现“Ld”字样。然后松开两个按钮。屏幕应该显示“rd”。如果没有出现“rd”，请重复此过程。',
		开始配对: '3. 开始配对',
		导航到下一个屏幕以开始配对过程: '进入到下一个屏幕以开始配对过程。',
		在可用蓝牙设备列表中: '在可用蓝牙设备列表中，选择',
		如果没有出现: '如果没有出现',
		点击屏幕顶部的刷新按钮: "点击屏幕顶部的刷新按钮。您可能需要刷新几次，直到设备出现。",
		手表配对说明: '手表配对说明',
		打开设备1: "1. 打开设备",
		接通手表电源: '接通手表电源。',
		确保手表靠近你的手机: '确保手表靠近你的手机，并且没有进入睡眠模式。',
		在可用蓝牙设备列表中: '在可用蓝牙设备列表中，选择',
		如果没有出现: '如果没有出现',
		点击屏幕顶部的刷新按钮: "点击屏幕顶部的刷新按钮。您可能需要刷新几次，直到设备出现。",
		如果出现超时: '注意:1.如果出现超时，请验证是否选择了正确的设备名称。如果选择了正确的名称，则可能偶尔发生此错误。只需再次点击设备名称即可重试连接。2.您可能还需要对手表进行重启操作。',
		请确认蓄电池已正确安装: '1. 请确认蓄电池已正确安装。',
		走到体重计上: '2. 走到体脂秤上，确认显示器处于亮屏状态。',
		保持在天平上: '3. 保持在体脂秤上，直到配对过程成功完成。',
		开始配对体脂称: '4. 开始配对',
		将体脂秤开机: '1、将体脂秤开机',
		打开蓝牙并授权蓝牙相关权限: '2、打开蓝牙并授权蓝牙相关权限',
		拒绝蓝牙相关权限将无法正常使用蓝牙相关功能: '注：拒绝蓝牙相关权限将无法正常使用蓝牙相关功能',
		帮助中心: '帮助中心',
		已绑定: '已绑定',
		未绑定: '未绑定',
		头像设置: '头像设置',
		从手机相册选择: '从手机相册选择',
		选择头像: '选择头像',
		已连接过的设备: '已连接过的设备',
		未连接过的设备: '未连接过的设备',
		配对成功: '配对成功',
		蓝牙已连接成功: "蓝牙已连接成功",
		蓝牙搜索页面: '蓝牙搜索页面',
		刷新: '刷新',
		正在配对: "正在配对",
		型号: '型号:',
		绑定型号1: '当前是绑定体脂秤页面,请扫描正确的体脂秤设备码',
		绑定型号2: '当前是绑定血压计页面,请扫描正确的血压计设备码',
		知道了: '知道了',
		编辑数据卡片: '编辑数据卡片',
		本页面显示均为最近测量数据: '注:本页面显示均为最近测量数据',
		体围数据: '体围数据',
		单位: '单位：CM',
		胸围: '胸围',
		腰围: '腰围',
		臀围: '臀围',
		上臂围: '上臂围',
		大腿围: '大腿围',
		小腿围: '小腿围',
		确保每天摄入足够的水: '确保每天摄入足够的水，避免因口渴误以为饥饿。',
		首页: '首页',
		今天: '今天',
		记体重: '记体重',
		记体围: '记体围',
		手动输入: '手动输入',
		请输入收缩压: '请输入收缩压',
		请输入舒张压: '请输入舒张压',
		请输入脉搏: '请输入脉搏',
		滑动输入: '滑动输入',
		请输入胸围: '请输入胸围',
		请输入腰围: '请输入腰围',
		请输入臀围: '请输入臀围',
		请输入上臂围: '请输入上臂围',
		请输入大腿围: '请输入大腿围',
		请输入小腿围: '请输入小腿围',
		请输入体重: '请输入体重',
		请输入目标体重: '请输入目标体重',
		年: '年',
		月: '月',
		日: '日',
		时: '时',
		分: '分',
		周: '周',
		选择管理类型: '选择管理类型',
		拒绝: '拒绝',
		暂不选择: '暂不选择',
		绑定设备后测量数据将自动上传: "绑定设备后测量数据将自动上传。",
		在绑定设备前: '在绑定设备前,请您充分阅读、理解',
		并同意以下协议政策: '并同意以下协议政策。',
		JakobLife软件移动客户端用户使用规范: '《JakobLife软件移动客户端用户使用规范》',
		JakobLife隐私政策: '《JakobLife隐私政策》',
		敏感个人信息处理情况的说明: '《敏感个人信息处理情况的说明》',
		向第三方提供个人信息情况的说明: '《向第三方提供个人信息情况的说明》',
		我已阅读并同意: '我已阅读并同意',
		我确认已满14周岁: '我确认已满14周岁',
		勾选表示已阅读并同意: '勾选表示已阅读并同意',
		请同意使用协议: '请同意使用协议',
		使用协议: '使用协议',
		欢迎使用: '欢迎使用',
		服务协议和隐私政策: '服务协议和隐私政策',
		服务协议和隐私政策1: '1.请你务必审慎阅读、充分理解“服务协议”和“隐私政策”各条款，包括但不限于：为了更好的向你提供服务，我们需要收集你的设备标识、操作日志等信息用于分析、优化应用性能。',
		你可阅读: '2.你可阅读',
		服务协议: '《服务协议》',
		服务协议1: '服务协议',
		和: '和',
		或: '或',
		隐私政策: '《隐私政策》',
		服务协议和隐私政策2: '了解详细信息。如果你同意，请点击下面按钮开始接受我们的服务。',
		同意并接受: '同意并接受',
		请填写图形验证码: '请填写图形验证码',
		请输入图形验证码: '请输入图形验证码',
		看不清: '看不清？换一张',
		确定: '确定',
		取消: '取消',
		请输入验证码结果: '请输入验证码结果',
		不能重复获取: '不能重复获取',
		s后可重发: 's后可重发',
		重新获取: '重新获取',
		请同意服务协议: '请同意服务协议',
		添加失败请重试: '添加失败,请重试。',
		重新绑定: '重新绑定',
		绑定失败: "绑定失败？",
		绑定失败1: '1、请确保按照标识正确插入SIM卡在设备中，并检查网络连接是否正常，若无信号请在关机状态下重新插入SIM卡；',
		绑定失败2: '2、请扫描机身标贴的IMEI码或包装彩盒标贴的二维码重新绑定；',
		绑定失败3: '3、重启设备进行尝试；',
		绑定失败4: '4、若仍无法绑定，请拨打我们的服务热线0755-86561393。',
		请将条码放入扫码框内即可自动扫描: '请将条码放入扫码框内，即可自动扫描',
		请扫描设备的设备码: '请扫描设备的设备码',
		当前主页面已绑定该设备: '当前主页面已绑定该设备',
		绑定成功: '绑定成功',
		绑定设备中请不要退出app: '绑定设备中,请不要退出app',
		设备绑定成功: '设备绑定成功!',
		请选择血压计型号: '请选择血压计型号',
		请选择体脂秤型号: '请选择体脂秤型号',
		暂无设备型号数据: '暂无设备型号数据',
		未选: '未选',
		准备就绪: '准备就绪',
		下一步: '下一步',
		是否准备就绪: '是否准备就绪',
		在待机状态下: '2、在待机状态下按“设定”和“记忆”键，随后WiFi图标开始闪烁，进入配网模式。',
		请勿连接名称前有5G的WIFI: '请勿连接名称前有“5G”的WIFI',
		请选择wifi: '请选择wifi',
		WIFI密码: "WIFI密码:",
		请输入wifi密码: '请输入wifi密码',
		开始连接: '开始连接',
		请选择或者输入一个wifi: '请选择或者输入一个wifi',
		为设备连接WiFi: '为设备连接WiFi',
		蓝牙设备绑定: '蓝牙设备绑定',
		蓝牙设备绑定1: '1、打开手机设置，进入蓝牙连接；',
		蓝牙设备绑定2: '2、选择对应设备型号进行连接。',
		我已完成连接: '我已完成连接',
		当前蓝牙未开启: "当前蓝牙未开启，是否去设置打开？",
		请输入手机号: '请输入手机号',
		完成: '完成',
		绑定手机号: '绑定手机号',
		绑定手机号1: '绑定手机号',
		请输入您新绑定的手机号: '请输入您新绑定的手机号',
		请输入您新绑定的邮箱: '请输入您新绑定的邮箱',
		新手机号验证: '新手机号验证',
		新邮箱验证: '新邮箱验证',
		重置密码: '重置密码',
		再次输入的密码未设置: '再次输入的密码未设置',
		密码不能低于8位数: '密码不能低于8位数',
		两次输入的密码不一致: '两次输入的密码不一致',
		密码已重置成功: '密码已重置成功,请重新登录!',
		新号码已绑定成功: '新号码已绑定成功!',
		新手机号绑定: '新手机号绑定',
		恭喜您: '恭喜您，注册成功!',
		建议您完善以下信息: '建议您完善以下信息，以下信息将用于基础分析。',
		出生日期: '出生日期',
		请输入: '请输入',
		男: '男',
		女: '女',
		请选择: '请选择',
		请选择性别: '请选择性别',
		请选择出生日期: '请选择出生日期',
		请输入身高: '请输入身高',
		请输入体重: '请输入体重',
		注册: '注册',
		请输入会员名: '请输入会员名',
		请输入不小于八位数密码: '请输入不小于八位数密码',
		会员名未设置: '会员名未设置',
		密码未设置: '密码未设置',
		请阅读并同意JakobLife软件服务使用协议: "请阅读并同意《JakobLife软件服务使用协议》",
		关于更新: '关于&更新',
		当前版本: '当前版本:',
		备案号: '备案号:苏ICP备2024092533号-2A',
		备案号1: '备案号',
		给JakobLife好评: '给JakobLife好评',
		JakobLife软件移动客户端用户使用规范1: 'JakobLife软件移动客户端用户使用规范',
		JakobLife隐私政策1: 'JakobLife隐私政策',
		敏感个人信息处理情况说明1: '敏感个人信息处理情况说明',
		向第三方提供个人信息情况的说明1: '向第三方提供个人信息情况的说明',
		已收集个人信息清单1: '已收集个人信息清单',
		第三方共享个人清单1: '第三方共享个人清单',
		医疗器械使用安全提示1: '医疗器械使用安全提示',
		选取歌曲: '选取歌曲',
		铃声: '铃声',
		雷达: '雷达(默认)',
		波浪: '波浪',
		倒影: '倒影',
		灯塔: '灯塔',
		山顶: '山顶',
		水晶: '水晶',
		无: '无',
		款体脂秤绑定教程: '4G款体脂秤绑定教程',
		网络连接: 'TSB-617B-T、JL-BP67G、JL-BP68G为4G网络连接',
		款体脂秤绑定不了: '4G款体脂秤绑定不了',
		WIFI款体脂秤绑定教程: 'WIFI款体脂秤绑定教程',
		WIFI款体脂秤绑定不了: 'WIFI款体脂秤绑定不了',
		网络连接1: "JL-BP67W、JL-BP68W为WIFI网络连接",
		体脂秤绑定问题: '体脂秤绑定问题',
		已解决: '已解决',
		继续反馈: '继续反馈',
		数据同步失败: '数据同步失败',
		数据同步等待时间长: '数据同步等待时间长',
		注销账号: '注销账号',
		您账号下的JakobLife账号: '您账号下的JakobLife账号！',
		安全验证: '安全验证',
		您的JakobLife账号服务权益处于安全状态: '您的JakobLife账号服务权益处于安全状态。',
		提前保留重要信息: '提前保留重要信息',
		由您本人发起: '由您本人发起，且注销前，您应自行处理相关数据及信息，如NFC或eSIM卡等虚拟服务中的个人数据。',
		请您谨慎操作: '请您谨慎操作',
		账号注销后: '账号注销后，所有数据将被彻底删除且无法恢复',
		账号注销服务: '账号注销服务，不会影响您后续对JakobLife产品或服务的使用。',
		注销JakobLife账号: '注销JakobLife账号',
		您将放弃以下资产或权益: '您将放弃以下资产或权益！',
		该账号所有的数据将被清空: '该账号所有的数据将被清空',
		所有设备会与您当前登录的账号解除绑定: '所有设备会与您当前登录的账号解除绑定，并清除设备之前存储在服务端的数据。',
		在手机中: '在手机中，账户的缓存数据将被清除',
		同时: '同时，还将撤销您对用户协议和隐私政策的同意，并退出JakobLife应用。',
		本人已阅读并同意注销协议: '本人已阅读并同意注销协议',
		再想想: '再想想',
		确认注销: '确认注销',
		请输入您原来的绑定的手机号: '请输入您原来的绑定的手机号',
		请输入您原来的绑定的邮箱: '请输入您原来的绑定的邮箱',
		原手机号不可用: '原手机号不可用？',
		原邮箱不可用: '原邮箱不可用？',
		使用其他方法验证: '使用其他方法验证。',
		原手机号验证: '原手机号验证',
		原邮箱验证: '原邮箱验证',
		数据同步: "数据同步",
		删除该设备: '删除该设备',
		添加设备: '添加设备',
		未选择: '未选择',
		当前已经绑定该设备: '当前已经绑定该设备',
		请选择一个设备: "请选择一个设备",
		头像: '头像',
		会员名: '会员名',
		身体基础信息: '身体基础信息',
		健康档案: '健康档案',
		未登录: '未登录',
		传统血压计使用指南: '传统血压计使用指南',
		传统血压计问题解答: '传统血压计问题解答',
		体脂秤使用指南: '体脂秤使用指南',
		体脂秤问题解答: '体脂秤问题解答',
		想和您共享健康数据: '请求与您共享他/她的健康数据',
		接受: "接受",
		已与您共享健康数据: '与您共享他/她的健康数据',
		请输入新的会员名: "请输入新的会员名",
		会员名修改: '会员名修改',
		暂无消息: '暂无消息',
		我的健康档案: '我的健康档案',
		单位设置: '单位设置',
		设备管理: '设备管理',
		提醒设置: '提醒设置',
		警报: '警报',
		低压报警: '低压报警',
		高压报警: '高压报警',
		警报使用提示1: '如果任何测量值超出上述正常范围，将触发警报。',
		警报使用提示2: '使用每个用户旁边的复选框为该用户启用或禁用警报通知。',
		用户: '用户',
		用户1: '自己',
		通知标题: '通知标题',
		警报内容: '警报内容',
		测量通知: '测量通知',
		舒张压有未录入: '舒张压有未录入',
		收缩压有未录入: '收缩压有未录入',
		脉搏有未录入: '脉搏有未录入',
		血氧有未录入: '血氧有未录入',
		血氧最大值不能超过: '血氧最大值不能超过100',
		安全中心: '安全中心',
		我的: "我的",
		暂无数据: '暂无数据',
		时间: '时间',
		重复: '重复',
		标签: '标签',
		震动: '震动',
		稍后提醒: '稍后提醒',
		保存: '保存',
		选择重复时间: '选择重复时间',
		请填写标签: '请填写标签',
		请选择铃声: '请选择铃声',
		保存成功: '保存成功',
		未设置会员名: '未设置会员名',
		永不: '永不',
		设置登录密码: '设置登录密码',
		第三方账号绑定: '第三方账号绑定',
		微信: '微信',
		退出登录: '退出登录',
		款血压计绑定教程: '4G款血压计绑定教程',
		款血压计绑定不了: '4G款血压计绑定不了',
		WIFI款血压计绑定教程: 'WIFI款血压计绑定教程',
		WIFI款血压计绑定不了: 'WIFI款血压计绑定不了',
		网络问题2: 'TSB-617B-T、JL-BP67G、JL-BP68G为4G网络连接',
		网络问题3: 'JL-BP67W、JL-BP68W为WIFI网络连接',
		公斤: 'lb',
		斤: 'kg',
		他人与我共享: '他人与我共享',
		暂无用户与您共享健康数据: '暂无用户与您共享健康数据。',
		健康共享: '健康共享',
		掌握权在您手中: '掌握权在您手中',
		安全共享您的健康数据: '安全共享您的健康数据，使亲友及时了解您的健康状况。',
		图标汇总和通知: '图标汇总和通知',
		您共享的数据将在其: '您共享的数据将在其“JakobLife”App中显示。\n有更新时还可以向共享对象发送通知',
		私密且安全: '私密且安全',
		仅分享每个主题的摘要: '仅分享每个主题的摘要，而非详细信息。信息会加密，您可以随时停止共享。',
		共享对象: '共享对象，需同样下载“JakobLife”App,并持有账号，否则无法共享。',
		您正在与: '您正在与',
		共享以下健康数据: '共享以下健康数据',
		正在与您共享以下健康数据: '正在与您共享以下健康数据',
		注本页面显示均为最近测量数据: '注：本页面显示均为最近测量数据',
		编辑: '编辑',
		共享: '共享',
		趋势: '趋势',
		您将与: '您将与',
		您始终可以更改共享或停止共享: "您始终可以更改共享或停止共享，若停止共享，您的数据将从其设备上移除。",
		全选: '全选',
		请选择要共享的数据: '请选择要共享的数据',
		取消共享: '取消共享',
		请搜索会员名或手机号: '请搜索会员名或手机号',
		此账号异常登录: '此账号异常登录',
		删除记录: '删除记录',
		动态血压监测报告仅支持导出单日数据: "动态血压监测报告仅支持导出单日数据",
		导出的数据时间不能超过一年: '导出的数据时间不能超过一年',
		确保每天摄入足够的水: '确保每天摄入足够的水，避免因口渴误以为饥饿。',
		增重速度: '增重速度',
		您的身体数据均为正常请继续保持: '您的身体数据均为正常,请继续保持',
		分钟240: '240分钟',
		分钟30: '30分钟',
		分钟60: '60分钟',
		分钟90: '90分钟',
		分钟120: '120分钟',
		小时以上2: '2小时以上',
		请选择报告日期: '请选择报告日期',
		请选择起床时间: '请选择起床时间',
		请选择就寝时间: '请选择就寝时间',
		请选择是否午休: '请选择是否午休',
		请选择午休时长: '请选择午休时长',
		请选择是否服用药物: '请选择是否服用药物',
		请选择当前用药: '请选择当前用药',
		请选择工作是否倒班: '请选择工作是否倒班',
		请注意: '*请注意:本报告及相关建议仅供参考，如有任何健康问题或疑虑，请务必咨询医生或其他专业医疗人士。',
		检测设备: '检测设备',
		日期: '日期',
		动态血压趋势图: '动态血压趋势图',
		次: '次',
		动态血压监测统计表: '动态血压监测统计表',
		白天清醒时段: '白天清醒时段',
		夜间睡眠时段: '夜间睡眠时段',
		起床后清晨时段: '起床后清晨时段',
		有效数据个数: '有效数据个数(百分比)',
		均值: '均值',
		标准差: '标准差',
		最大值: '最大值',
		中位数: '中位数',
		最小值: '最小值',
		血压负荷: '血压负荷',
		夜间血压下降率: '夜间血压下降率',
		血压晨峰: '血压晨峰',
		变异系数: '变异系数',
		动脉硬化指数: '动脉硬化指数',
		盐敏感可能性: '盐敏感可能性',
		动态血压监测相关图: '动态血压监测相关图(24h)',
		有效测量次数: '有效测量次数',
		总计监测时间: '总计监测时间',
		有效监测时间: '有效监测时间',
		告知1: '舒张压=5.94+0.60x收缩压',
		告知2: '收缩压和舒张压的相关性：r=0.84，收缩压和舒张压呈高度线性正相关',
		动态血压监测数据统计: '动态血压监测数据统计',
		手动输入数据: '手动输入数据',
		无效数据: '无效数据',
		睡眠时段测量数据: '睡眠时段测量数据(含午睡和夜间)',
		血压分析和建议: '血压分析和建议',
		分析: '分析:',
		分析1: '收缩压夜间血压下降率为“反杓型”',
		分析2: '收缩压夜间血压下降率为“非杓型”',
		分析3: '收缩压夜间血压下降率为“超杓型”',
		分析4: '收缩压夜间血压下降率为“杓型”',
		分析5: '24小时收缩压血压负荷异常',
		分析6: '晨峰血压异常',
		分析7: '动脉硬化风险较高',
		分析777: '动脉硬化指数升高会带来多种健康风险，以下是具体分析：\n1.动脉硬化指数的定义及正常范围动脉硬化指数（ AI） 是通过计算血液中总胆固醇（ TC） 与高密度脂蛋白胆固醇（ HDL -C） 的比值来评估动脉硬化程度的指标。 正常情况下， AI应小于4， 若指数超过4， 则提示动脉硬化程度较高， 并可能增加相关疾病的风险。\n2.健康风险的具体表现动脉硬化指数升高可能导致以下健康问题：心血管疾病： 如冠心病、 心绞痛、 心肌梗死等。 当动脉硬化发生在心脏的冠状动脉时， 会引发血管狭窄或阻塞， 导致心肌供血不足， 甚至危及生命。脑血管疾病： 如脑梗死、 脑卒中等。 如果硬化发生在脑部血管， 可能导致脑供血不足， 引发脑卒中。肾脏功能障碍： 肾脏血管的硬化可能导致肾功能下降， 严重时可能引发肾衰竭。眼底病变： 眼底血管硬化可能影响视力， 导致视网膜病变。其他并发症： 如外周动脉疾病， 导致肢体疼痛、 麻木， 甚至坏疽。\n3.健康风险的形成原因动脉硬化指数升高的原因包括：不良生活习惯： 如长期高脂饮食、 缺乏运动、 吸烟、 酗酒等。基础疾病： 如高血压、 高胆固醇血症、 糖尿病等， 这些疾病会加速动脉硬化的进程。遗传因素： 某些人群因遗传原因更容易出现脂质代谢异常， 导致动脉硬化指数升高。\n4.预防和管理建议针对动脉硬化指数升高， 可以采取以下措施：调整饮食结构： 减少高脂肪、 高胆固醇食物的摄入， 增加富含膳食纤维的食物（ 如蔬菜、 水果、 全谷物）， 并适量摄入不饱和脂肪酸（ 如鱼类和坚果）。适量运动： 每周进行至少150分钟的中等强度有氧运动， 如快走、 游泳、 骑自行车等， 以促进血液循环和代谢。戒烟限酒： 戒烟可以减少血管内皮损伤， 限制饮酒有助于控制血压和血脂。控制体重： 将体重维持在健康范围内， 避免超重或肥胖。定期体检： 监测血压、 血脂、 血糖等指标， 及时调整生活方式或进行医学干预。药物治疗： 在医生指导下使用降脂药物（ 如他汀类药物）、 抗血小板药物（ 如阿司匹林） 等， 以延缓动脉硬化进展。\n5.总结动脉硬化指数升高是心血管疾病和其他相关健康问题的重要风险因素。 通过健康的生活方式、 定期体检以及必要的医学干预， 可以有效降低其风险， 维护血管健康。 如果您已检测到指数偏高， 建议及时就医， 制定个性化的治疗方案。 ',
		分析8: '白天时段收缩压异常',
		分析9: '24小时有效测量次数不够',
		分析10: '白天时段有效测量次数不够',
		分析a: '夜间时段有效测量次数不够',
		分析81: '白天时段舒张压异常',
		分析82: '白天时段血压异常',
		分析83: '夜间时段收缩压异常',
		分析84: '夜间时段舒张压异常',
		分析85: '夜间时段血压异常',
		分析86: '清晨时段收缩压异常',
		分析87: '清晨时段舒张压异常',
		分析88: '清晨时段血压异常',
		分析91: '24小时血压异常',
		分析101: '24小时收缩压异常',
		分析aa: '24小时舒张压异常',
		分析11: '舒张压夜间血压下降率为“反杓型”',
		分析22: '舒张压夜间血压下降率为“非杓型”',
		分析33: '舒张压夜间血压下降率为“超杓型”',
		分析44: '舒张压夜间血压下降率为“杓型”',
		分析52: '白天时段收缩压血压负荷异常',
		分析53: '夜间时段收缩压血压负荷异常',
		分析54: '清晨时段收缩压血压负荷异常',
		分析55: '24小时舒张压血压负荷异常',
		分析56: '白天时段舒张压血压负荷异常',
		分析57: '夜间时段舒张压血压负荷异常',
		分析58: '清晨时段舒张压血压负荷异常',
		建议: '建议:',
		建议1: '1. 风险最高的类型：表示夜间交感神经活性持续升高，心脏负担大。\n2. 缺血性卒中、心力衰竭、猝死的发生率显著升高。\n3.常见于高危人群（失眠、OSA、阿尔茨海默病、帕金森病、糖尿病晚期等）。\n4.是预测中风复发和死亡率的重要独立危险因素。',
		建议2: '1. 高血压相关靶器官损害：左心室肥厚、肾功能损害、动脉粥样硬化。\n2. 心脑血管事件风险增加：如中风、心肌梗死。\n3. 常见于以下人群：\n -老年人；\n -糖尿病患者；\n-睡眠呼吸障碍（如OSA）；\n-慢性肾病患者；\n4. 非杓型高血压患者心脑血管事件发生率高于杓型 2~3 倍。',
		建议3: '1. 风险较高，尤其是脑灌注不足风险。\n2. 夜间血压过低，容易造成脑缺血、老年人跌倒、清晨卒中等。\n3. 多见于长期服用降压药，尤其是剂量或药效时程控制不当者。',
		建议4: '1. 代表交感神经活动夜间正常降低，血管调节功能良好。\n2. 属于健康的血压昼夜节律，心血管风险最低。',
		建议5: '1. 心脑血管事件风险显著升高。\n2. 靶器官损伤风险。\n3. 早期动脉硬化风险。\n4. 儿童与青少年早期损害。\n5. 预测隐匿性高血压与白大衣高血压。 ',
		建议6: '晨起时段高血压患者的心脑血管事件风险显著升高，如果晨起血压控制不良，发生心绞痛、心肌梗死、脑卒中等严重并发症的风险会大大增加。',
		建议7: '冠心病（心肌梗死、心绞痛）、脑卒中（缺血性脑梗）、外周动脉疾病（PAD）的风险升高。',
		建议8: '有高血压风险',
		建议9: '增加24小时测量次数',
		建议10: '增加白天时段测量次数',
		建议11: '增加夜间时段测量次数',
		您的身体健康暂无分析数据: '您的身体健康暂无分析数据',
		是否下载动态血压监测报告: '是否下载动态血压监测报告?',
		序号: '序号',
		平均动脉压: '平均动脉压',
		正常高值血压: '正常高值血压',
		创建我的帐户: '创建我的帐户',
		请确认密码: '请确认密码',
		注册账号已存在: '注册账号已存在',
		成功: '成功',
		请输入邮箱: '请输入邮箱',
		绑定邮箱: '绑定邮箱',
		绑定邮箱1: '绑定邮箱',
		厘米: 'm',
		请输入会员名或邮箱: '请输入会员名或绑定的邮箱',
		监测时间: '监测时间',
		监测时间在1天之内: "监测时间在1天之内",
		监测时间在2天之内: "监测时间在2天之内",
		监测时间在3天之内: "监测时间在3天之内",
		监测时间在4天之内: "监测时间在4天之内",
		监测时间在5天之内: "监测时间在5天之内",
		监测时间在6天之内: "监测时间在6天之内",
		监测时间在当周之内: "监测时间在当周之内",
		监测时间在前2周之内: "监测时间在前2周之内",
		监测时间在前3周之内: "监测时间在前3周之内",
		监测时间在当月之内: "监测时间在当月之内",
		监测时间在前2月之内: "监测时间在前2月之内",
		监测时间在前3月之内: "监测时间在前3月之内",
		请选择监测时间: '请选择监测时间',
		失败: '失败',
		软件更新: '软件更新',
		请您阅读并同意注销协议: '请您阅读并同意注销协议',
		注销提示: '注销提示',
		请确认是否注销JakobLife账号: '请确认是否注销JakobLife账号',
		账户不存在或密码错误: '账户不存在/密码错误',
		设备: '设备',
		提示: '提示',
		确认移除此设备: '确认移除此设备',
		确认移除此设备1: '如果你在配对过程中连接了经典蓝牙，请进入手机的蓝牙设置，手动设置“忘记设备”。',
		确认移除此设备2: "请在解绑过程中，臂式血压计一直保持亮屏状态",
		版本更新1: '新版本号',
		版本更新2: '可供更新',
		当前下载进度: '当前下载进度',
		已经是最新版本1: '版本号 ',
		已经是最新版本2: '已经是最新版本',
		当前蓝牙未开启是否去设置打开: '当前蓝牙未开启，是否去设置打开？',
		数据不存在: '数据不存在',
		血压手表使用指南: '血压手表使用指南',
		血压手表问题解答: '血压手表问题解答',
		连接超时: '连接超时',
		此用户不存在: "此用户不存在",
		您已向: '您已向',
		发出共享健康数据邀请: '发出共享健康数据邀请',
		搜索: '搜索',
		血压分类: '血压分类',
		根据WHOISH的血压分类2020年修订版: '根据WHO/ISH的血压分类(2020年修订版)',
		和或: '和/或',
		血压范围: '血压范围',
		血压类别: '血压类别',
		生成健康报告: '生成健康报告',
		血压水平偏低: '血压水平偏低',
		血压水平正常: '血压水平正常',
		血压水平偏高: '血压水平偏高',
		三级高血压: '三级高血压',
		该邮箱已被绑定: '该邮箱已被绑定',
		该手机号已被绑定: "该手机号已被绑定",
		选中的设备与扫码设备不匹配: '选中的设备与扫码设备不匹配',
		至少选择一个选项: '至少选择一个选项',
		设置新的正常范围: '设置新的正常范围',
		设定成功: '设定成功',
		这个类别没有任何连接设备: '这个类别没有任何连接设备',
		体温: '体温',
		压力: '压力',
		血压计注意事项: '请在用此臂式电子血压计测量血压时停留在主界面，并保持手机亮屏状态。这样可以确保是您本人在进行测试，而不是其他人。',
		体脂秤注意事项: '在使用体脂秤测量时，请保持手机屏幕处于亮屏状态。若屏幕关闭，数据可能无法与蓝牙广播设备正常同步。Jakoblif‌e 其他设备支持屏幕关闭时的数据同步。',
		手表注意事项: '这款手表使用低功耗蓝牙来延长电池寿命。在此模式下，无法接听来电。如果您想接听电话， 请在您的手表上启用经典蓝牙。 然后， 通过手机的蓝牙设置手动连接手表。 设备将显示为BPW1。 ',
		网络连接异常: '没有互联网连接，数据将无法与手机和云同步',
		短信验证成功: '短信验证成功',
		邮箱验证成功: '邮箱验证成功',
		不知道设备型号: '不知道设备型号？',
		心血管: '心血管',
		情绪: '情绪',
		运动: '运动',
		自动血压监测设置: '自动血压监测设置',
		开始时间: '开始时间',
		结束时间: '结束时间',
		设置自动血压监测: '设置自动血压监测',
		间隔时间: '间隔时间',
		关闭自动监控: '关闭自动监测',
		关闭成功: '关闭成功',
		打印: '打印',
		去设置: '去设置',
		删除: '删除',
		容易: '极低',
		低压: '低压',
		适度的压力: '适度的压力',
		高度的压力: '高度的压力',
		跳转设置: '跳转设置',
		是否跳转到蓝牙设置页面: '是否跳转到蓝牙设置页面？',
		手动选择: '手动选择',
		扫码绑定: '扫码绑定',
		BMI: 'BMI',
		此为血压计数据生成的报告不准确: '此为血压计数据生成的报告，不准确',
		显示结果弹窗: '结果显示您的血压可能偏高。我们建议您每天至少测量一次血压。',
		提示检测到血压偏高: '提示：检测到血压偏高我们的记录显示，您的血压已连续三天以上每天至少有一次高于正常水平。我们建议您使用我们的血压监测手表进行持续监测，以帮助改善健康状况。如果您尚未服用降压药，请考虑咨询医生，探讨是否需要开始治疗。如果您已经在服药，请咨询医生是否需要调整药物剂量或服药时间。通过手表进行持续监测，可帮助识别血压高峰时段，从而优化用药时间，提高治疗效果。',
		提示检测到血压偏高1: '提示：检测到血压偏高我们的记录显示，您的血压已连续三天以上每天至少有一次高于正常水平。如果您尚未服用降压药，请考虑咨询医生，探讨是否需要开始治疗。如果您已经在服药，请咨询医生是否需要调整药物剂量或服药时间。通过手表进行持续监测，可帮助识别血压高峰时段，从而优化用药时间，提高治疗效果。',
		收起: '收起',
		展开更多: '展开更多',





	},
	'en-US': {
		刷新中: 'Refreshing...',
		刷新失败: 'Refresh failed.',
		注销成功: 'Deletion successful.',
		注销失败: 'Deletion failed.',
		标准蓝牙提示1: 'Before normal use, press the middle button on the blood pressure monitor repeatedly until the screen turns off to exit pairing mode.',
		您的帐户有绑定: 'Your account is linked to one or more devices or is sharing data with others. Please unbind the devices and stop sharing before canceling your account.',
		手表如何监测睡眠情况: 'How to monitor your sleep in the watch',
		连接失败: 'Binding failed, please tap on your device’s model and try again.\nIf multiple attempts are unsuccessful, turn the device off and then on again. Follow the instructions on the previous page to re-enter pairing mode, and then select the device model.',
		没找到指定设备: 'The specified device was not found/The device has been connected.',
		请点击重试: "Please click “Retry”. If you still can't connect, please clear the app from the background of your phone and then reopen it to bind.",
		此设备已被其他账号绑定: 'This SN is linked to a different account',
		血压计说明书: 'BP Instruction Manual',
		手表说明书: 'Watch Instruction Manual',
		调整表带松紧度的简单方法: 'A Simple Way to Adjust the Strap Length',
		如何把表带末端的扣取出和放入: 'How to Remove and Lock the End Buckle Easily',
		如何在手表关闭经典蓝牙: 'How to Disable Classic Bluetooth on the Smartwatch',
		如何用手表上打电话: 'How to Make a Call on the Watch',
		如何在血压计上切换用户: 'How to Switch Between Users on the Blood Pressure Monitor',
		如何查看血压计的历史数据: 'How to View Historical Data on the Blood Pressure Monitor',
		请求失败: 'Request failed.',
		解绑失败: 'Unbinding failed.',
		设备已解绑: 'The device has been unbound.',
		臂式血压计的安装: 'Getting Started with Your Upper Arm Blood Pressure Monitor',
		臂式血压计的测试方法: 'How to Measure Your Blood Pressure Using a BP Monitor',
		设置臂式血压计的方法: 'Configuring Settings on Your Blood Pressure Monitor',
		臂式血压计如何和手机APP配对: 'How to Connect Your Blood Pressure Monitor to the Mobile App',
		血压计手表测量血压的方法: 'Jakoblife BPW1 Blood Pressure Smart Watch Instructions for Taking BP tests ',
		恢复血压计手表出厂设置: 'Resetting Your Blood Pressure Watch to Factory Settings',
		血压计手表如何和手机APP配对: 'How to Connect Your Blood Pressure Watch to the Mobile App',
		如何在血压计手表上设置自动血压测试: 'How to Set Up Automatic Blood Pressure Monitoring on Your Smartwatch',
		如何在血压计手表主页上加应用: 'How to Add Apps to Your Smartwatch Home Screen',
		如何设置血压计手表的语言: 'How to Change the Language Settings on Your Blood Pressure Watch',
		用血压计手表测血压前要检测的两个要点: '2 Key Things to Check Before Taking a Blood Pressure Test with Your Watch',
		如何和其他用户共享数据和设置远程警告: 'How to Share Health Data with Others and Configure Remote Alerts',
		获取相机权限成功: 'Camera permission obtained successfully.',
		扫码需要相机权限: 'Scanning requires camera permission; otherwise, scanning cannot be performed.',
		标准蓝牙提示: 'Note: To receive phone calls and messages, please select "Pair" in the next dialog box to enable classic Bluetooth. Please be aware that using classic Bluetooth may significantly reduce battery life. If you select "Cancel," low-energy Bluetooth will be used instead, offering extended battery life. While low-energy Bluetooth still allows data transfer to the app, it does not support receiving phone calls or messages.\nDuring the pairing process, the watch may automatically enable Classic Bluetooth. After pairing is complete, make sure to manually disable Classic Bluetooth on the watch to ensure it remains in low-power mode. For detailed steps on how to disable Classic Bluetooth, please refer to the Instructions section in the Help Center.',
		您好: "Hi",
		欢迎来到JakobLife: "Welcome to JakobLife",
		请输入会员名或绑定的手机号: "Username/Phone/Email",
		请输入绑定的手机号或绑定的邮箱: 'Phone/Email',
		请输入密码: "Password",
		忘记密码: "Forgot PW?",
		验证码登录: "Code Login",
		密码登录: "PW Login",
		获取验证码: "Get Code",
		已阅读并同意: "I agree to",
		JakobLife软件服务使用协议: "《JakobLife Terms》",
		请输入验证码: "Verification Code",
		登录: "Login",
		还没有JakobLife账号: "No account?",
		新用户去注册: "Register",
		其它登录方式: "Other Methods",
		添加数据卡片: "Add Card",
		拖动可调整数据卡片位置: "Drag to Rearrange",
		信息补充: "Details",
		相关信息: "Kindly confirm the following relevant information to ensure the accuracy and completeness of the detailed health reports and analysis.",
		报告日期: "Report Date",
		起床时间: "Wake-up",
		就寝时间: "Bedtime",
		是否午休: "Nap?",
		午休时长: "Nap Duration",
		是否服用药物: "Taking medications",
		当前用药: "Current Meds",
		工作是否倒班: "Shift Work?",
		跳过: "Skip",
		确认: "Confirm",
		是: "Yes",
		否: "No",
		动态血压监测报告: "ABPM Report",
		动态血压监测报告预览: 'ABPM Report Preview',
		姓名: "Name",
		性别: "Gender",
		年龄: "Age",
		最新体重: "Current Weight",
		初始体重: "Initial Weight",
		目标体重: "Target Weight",
		BMI分类: "BMI Category",
		根据世界卫生组织的最新BMI分类: "WHO BMI Classification (Latest)",
		BMI范围: "BMI Range",
		分类: "Category",
		体重过轻: "Underweight",
		正常体重: "Normal",
		超重: "Overweight",
		一级肥胖: "Obesity I",
		二级肥胖: "Obesity II",
		三级肥胖或病态肥胖: "Obesity III/Morbid",
		血氧分类: "SpO₂ Class",
		偏低: "Low",
		正常: "Normal",
		偏高: "High",
		平均: "Avg",
		最高: "Max",
		平均收缩压: "Avg SBP",
		平均舒张压: "Avg DBP",
		最近血压: "Recent BP",
		收缩压: "SBP",
		舒张压: "DBP",
		脉搏: 'HR',
		平均血压: "Mean BP",
		最高血压: "Max BP",
		最低血压: "Min BP",
		正常血压: "Normal BP",
		正常高血压值: "High-Normal BP",
		一级高血压: "Hypertension Stage 1",
		二级高血压: "Hypertension Stage 2",
		血氧: "SpO₂",
		骨含量: "Bone Mass",
		肌肉量: "Muscle Mass",
		蛋白率: "Protein%",
		水分: "Water%",
		内脏脂肪指数: "VFI",
		脂肪率: "Fat%",
		基础代谢率: "BMR",
		皮下脂肪率: "SubQ Fat%",
		身体年龄: "Body Age",
		岁: "y/o",
		身高: "Height",
		手表: 'Watch',
		体重: "Weight",
		步数: "Steps",
		计步: "Step Count",
		未知: "N/A",
		血氧1: "1.Note: Agitation, breath-holding or improper operation may affect SpO₂ accuracy",
		血氧2: "2.High SpO₂ (>98%): May indicate high oxygen intake with no clinical significance. Can reach 100% during oxygen therapy.",
		血氧3: "3.Low SpO₂ (<90%): Suggests possible hypoxia/hypoxemia.",
		选择管理1: "Please choose the relevant product category.",
		选择管理2: "You can switch focus later",
		选择管理3: "Select the measurements you would like to display",
		血压管理: "BP Mgmt",
		切换: 'Switch Measurement Category',
		体脂管理: "Body Fat Mgmt",
		当前未绑定任何设备: "No device connected",
		此账号还未绑定血压计设备: "No BP monitor linked",
		此账号还未绑定体脂秤设备: "No body scale linked",
		最近7天平均体重: "7-day avg weight",
		变化速度: "Change rate (kg/wk)",
		今日体重: "Today's weight",
		最高体重: "Max weight",
		最低体重: "Min weight",
		平均体重: "Avg weight",
		历史记录: "History",
		血压计: "BP",
		血压: "BP",
		心电: "ECG",
		体脂: "Body Fat",
		血糖: "Blood sugar",
		日历: "Calendar",
		列表: "List",
		帮助: "Help",
		回到今天: "Today",
		今: "Now",
		周一: "Mon",
		周二: "Tue",
		周三: "Wed",
		周四: "Thu",
		周五: "Fri",
		周六: "Sat",
		周日: "Sun",
		导出: "Export",
		导出设置: "Export Settings",
		导出格式: "Format",
		测量时间: "M-Time",
		注1: "Note: Max 1 year per export",
		开始日期: "Start Date",
		结束日期: "End Date",
		仅导出测量数据: "Export measurements only",
		生成动态血压监测报告: "Generate ABPM Report",
		注2: "Note: ABPM reports support single-day data only",
		消息: "Messages",
		清除: "Clear",
		邀请: "Invite",
		想与您共享健康数据: "wants to share health data",
		共享列表: "Shared List",
		共享给: "Shared With",
		与他人共享: "Share With Others",
		设备管理: "Devices",
		同意: "Agree",
		绑定设备: "Pair Device",
		确认绑定: "Confirm",
		暂不绑定: "Skip",
		绑定提醒1: "1.Insert SIM card correctly",
		绑定提醒2: "2.Scan device IMEI/QR code",
		绑定提醒3: "Scan device SN/QR code",
		打开: "ON",
		关闭: "OFF",
		将血压计开机: "1.Power on BP monitor",
		设备配对说明: 'Device Pairing Instructions',
		设备上电: "1. Power On",
		打开设备: 'Turn on the device.',
		准备配对: '2. Enter Pairing Mode',
		确保设备靠近你的手机: 'Press the right button to activate LCD, then press and hold both the left and right buttons simultaneously until “Ld” appears on the screen.Then release both buttons. The screen should display “rd.”If “rd” does not appear, please repeat the process.',
		开始配对: '3.  Begin Pairing',
		导航到下一个屏幕以开始配对过程: 'Navigate to the next screen to start the pairing process.',
		在可用蓝牙设备列表中: 'In the list of available Bluetooth devices, select',
		如果没有出现: 'If',
		点击屏幕顶部的刷新按钮: "does not appear, tap the Refresh button at the top of the screen.  You may need to refresh several times until the device appears.",
		手表配对说明: 'Watch Pairing Instructions',
		打开设备1: "1.Turn On the Device",
		接通手表电源: 'Power on the watch.',
		确保手表靠近你的手机: 'Ensure the watch is close to your phone and is not in sleep mode.',
		如果出现超时: 'Note:1.If a timeout occurs, please verify that the correct device name has been selected.  If the correct name was tapped, this error may occur occasionally.  Simply tap the device name again to retry the connection.2.You may also need to perform a power cycle on the watch.',
		请确认蓄电池已正确安装: '1.Ensure that the batteries are properly installed.',
		走到体重计上: '2.Step onto the body scale and confirm that the display is active.',
		保持在天平上: '3.Remain on the scale until the pairing process is successfully completed.',
		开始配对体脂称: '4.Begin Pairing',
		将体脂秤开机: "1.Power on body scale",
		打开蓝牙并授权蓝牙相关权限: "2.Enable Bluetooth",
		拒绝蓝牙相关权限将无法正常使用蓝牙相关功能: "Note: Denying BT permissions disables BT features",
		帮助中心: "Help Center",
		已绑定: "Paired",
		未绑定: "Unpaired",
		头像设置: "Profile Photo",
		从手机相册选择: "From Gallery",
		选择头像: "Select Photo",
		已连接过的设备: "Paired Devices",
		未连接过的设备: "New Devices",
		配对成功: "Paired Successfully",
		蓝牙已连接成功: "BT Connected",
		蓝牙搜索页面: "BT Search",
		刷新: "Refresh",
		正在配对: "Pairing...",
		型号: "Model:",
		绑定型号1: "Body scale pairing - scan correct device code",
		绑定型号2: "BP monitor pairing - scan correct device code",
		知道了: "OK",
		首页: "Home",
		今天: "Today",
		编辑数据卡片: "Edit Card",
		本页面显示均为最近测量数据: "Note: Shows recent measurements",
		体围数据: "Body Measurements",
		单位: "Unit: cm",
		胸围: "Chest",
		腰围: "Waist",
		臀围: "Hips",
		上臂围: "Arm",
		大腿围: "Thigh",
		小腿围: "Calf",
		手动输入: "Manual",
		滑动输入: "Slider",
		记体重: "Log Weight",
		记体围: "Log Measurements",
		请输入收缩压: "SBP",
		请输入舒张压: "DBP",
		请输入脉搏: "Pulse",
		请输入胸围: "Chest",
		请输入腰围: "Waist",
		请输入臀围: "Hips",
		请输入上臂围: "Arm",
		请输入大腿围: "Thigh",
		请输入小腿围: "Calf",
		请输入体重: "Weight",
		请输入目标体重: "Target Weight",
		确保每天摄入足够的水: "Stay hydrated to avoid thirst/hunger confusion",
		年: "Yr",
		月: "Mo",
		日: "Day",
		时: "Hr",
		分: "Min",
		周: "Wk",
		选择管理类型: "Add Devices",
		拒绝: "Decline",
		暂不选择: "Skip for Now",
		绑定设备后测量数据将自动上传: "Data auto-syncs when device bound.",
		在绑定设备前: "Before binding, please read and understand",
		并同意以下协议政策: "Please review and agree to:",
		JakobLife软件移动客户端用户使用规范: "《JakobLife User Agreement》",
		JakobLife隐私政策: "《JakobLife Privacy Policy》",
		敏感个人信息处理情况的说明: "《Sensitive Data Handling》",
		向第三方提供个人信息情况的说明: "《Third-Party Data Sharing》",
		我已阅读并同意: "I agree",
		我确认已满14周岁: "Age 14+ confirmed",
		勾选表示已阅读并同意: "Tick to agree",
		请同意使用协议: "Accept Terms",
		使用协议: 'User Agreement',
		欢迎使用: 'Welcome',
		服务协议和隐私政策: 'Terms & Privacy Policy',
		服务协议和隐私政策1: '1. Please carefully read both Terms and Privacy Policy, including but not limited to: To provide better service, we collect device IDs and usage logs for analytics and performance optimization.',
		你可阅读: '2. Review',
		服务协议: '《Terms of Service》',
		服务协议1: 'Terms of Service',
		和: 'and',
		或: 'or',
		隐私政策: '《Privacy Policy》',
		服务协议和隐私政策2: 'for details. Click below to accept.',
		同意并接受: 'Agree & Accept',
		请填写图形验证码: "Enter CAPTCHA",
		请输入图形验证码: "CAPTCHA",
		看不清: "Refresh",
		确定: "OK",
		取消: "Cancel",
		请输入验证码结果: "CAPTCHA Result",
		重新获取: "Resend",
		不能重复获取: "Wait to resend",
		s后可重发: "s remaining",
		请同意服务协议: "Check term agreement box",
		添加失败请重试: "Failed. Please retry.",
		重新绑定: "Rebind",
		绑定失败: "Binding failed?",
		绑定失败1: "1. Ensure that the SIM card is properly inserted for 4G/5G devices and that the network connection is stable. Additionally, for Bluetooth (BT) devices, confirm that Bluetooth is enabled on both the phone and the device.",
		绑定失败2: "2. Rescan device IMEI or QR code on packaging.",
		绑定失败3: "3. Restart device.",
		绑定失败4: "4. Still stuck? Please contact us at: jakoblife@jakob-techs.com.",
		请将条码放入扫码框内即可自动扫描: 'Position the barcode within the frame to scan',
		请扫描设备的设备码: 'Scan device ID',
		当前主页面已绑定该设备: 'Device already added',
		绑定成功: 'Bound successfully',
		绑定设备中请不要退出app: 'Please stay in app during binding',
		设备绑定成功: 'Device paired successfully!',
		请选择血压计型号: "Select BP Monitor Model",
		请选择体脂秤型号: "Select Body Fat Scale Model",
		暂无设备型号数据: "No Models Available",
		未选: "Not Selected",
		准备就绪: "Ready",
		下一步: "Proceed",
		是否准备就绪: "Confirm Ready Status",
		在待机状态下: "2.In standby mode, press 'Setup' & 'Memory' buttons. WiFi icon flashes, entering network config mode.",
		请勿连接名称前有5G的WIFI: "Avoid 5G-prefixed WiFi",
		请选择wifi: "Select WiFi",
		WIFI密码: "Password:",
		请输入wifi密码: "Enter WiFi password",
		开始连接: "Connect",
		请选择或者输入一个wifi: "Select or enter WiFi",
		为设备连接WiFi: 'Connect device to WiFi',
		蓝牙设备绑定: "Bluetooth Pairing",
		蓝牙设备绑定1: "1. Open phone Settings > Bluetooth",
		蓝牙设备绑定2: "2. Select your device model to connect",
		我已完成连接: "I’m connected",
		当前蓝牙未开启: "Bluetooth is off,Enable Bluetooth in Settings?",
		请输入手机号: "Phone Number",
		完成: "Done",
		绑定手机号: "Link Phone",
		绑定手机号1: "Linked Phone",
		请输入您新绑定的手机号: 'New phone number',
		请输入您新绑定的邮箱: 'New Email',
		新手机号验证: 'Verify number',
		新邮箱验证: 'Verify Email',
		重置密码: 'Reset Password',
		再次输入的密码未设置: "Repeat password not entered",
		密码不能低于8位数: "Password must be at least 8 characters in length",
		两次输入的密码不一致: "Passwords don't match",
		密码已重置成功: 'Password updated. Please log in again!',
		新号码已绑定成功: "New number linked!",
		恭喜您: "Congratulations! Registration Completed.",
		建议您完善以下信息: "Complete your profile for personalized insights:",
		新手机号绑定: "Link New Number",
		出生日期: "Birth Date",
		请输入: "Enter",
		男: "Male",
		女: "Female",
		请选择: "Select",
		请选择性别: "Gender",
		请选择出生日期: "Select Birth Date",
		请输入身高: "Height",
		请输入体重: "Weight",
		注册: 'Register',
		请输入会员名: "Username",
		请输入不小于八位数密码: "Password (8+ characters)",
		会员名未设置: "Username required",
		密码未设置: "Password required",
		请阅读并同意JakobLife软件服务使用协议: "I agree to the Terms of Service",
		关于更新: 'About & Updates',
		当前版本: 'Version:',
		备案号: 'ICP: Su-2024092533-2A',
		备案号1: 'ICP',
		给JakobLife好评: 'Rate JakobLife',
		JakobLife软件移动客户端用户使用规范1: 'JakobLife User Agreement',
		JakobLife隐私政策1: 'JakobLife Privacy Policy',
		敏感个人信息处理情况说明1: 'Sensitive Data Handling',
		向第三方提供个人信息情况的说明1: 'Third-Party Data Sharing',
		已收集个人信息清单1: 'Data Collection Summary',
		第三方共享个人清单1: 'Third-Party Recipients',
		医疗器械使用安全提示1: 'Medical Device Safety',
		选取歌曲: "Select Song",
		铃声: "Ringtone",
		雷达: "Radar (Default)",
		波浪: "Wave",
		倒影: "Reflection",
		灯塔: "Lighthouse",
		山顶: "Mountain",
		水晶: "Crystal",
		无: "None",
		款体脂秤绑定教程: "4G Scale Pairing Guide",
		网络连接: "TSB-617B-T, JL-BP67G, JL-BP68G use 4G",
		款体脂秤绑定不了: "4G Scale Won't Pair",
		WIFI款体脂秤绑定教程: "WiFi/BT Scale Pairing Guide",
		WIFI款体脂秤绑定不了: "WiFi/BT Scale Won't Pair",
		网络连接1: "JL-BP67W, JL-BP68W use WiFi",
		体脂秤绑定问题: "Scale Pairing Issues",
		已解决: "Solved",
		继续反馈: "Continue Feedback",
		数据同步失败: "Sync Failed",
		数据同步等待时间长: "Sync Taking Too Long",
		注销账号: "Delete Account",
		您账号下的JakobLife账号: "Your JakobLife Account",
		安全验证: "Security Verification",
		您的JakobLife账号服务权益处于安全状态: "Your account security status is verified.",
		提前保留重要信息: "Back Up Important Data",
		由您本人发起: "You must manually clear personal data (e.g., NFC/eSIM) before deletion.",
		请您谨慎操作: "Warning:",
		账号注销后: "All data will be permanently erased.",
		账号注销服务: "Account deletion won't affect future use of JakobLife services.",
		注销JakobLife账号: "Delete JakobLife Account",
		您将放弃以下资产或权益: "You'll lose:",
		该账号所有的数据将被清空: "• All account data",
		所有设备会与您当前登录的账号解除绑定: "Device unbinding and personal data is erased",
		在手机中: "• Local cache cleared",
		同时: "• Terms/Privacy Policy consent revoked",
		本人已阅读并同意注销协议: "I accept deletion terms",
		再想想: "Cancel",
		确认注销: "Confirm Deletion",
		请输入您原来的绑定的手机号: "Original phone number",
		请输入您原来的绑定的邮箱: "Original Email",
		原手机号不可用: "Can't use old number?",
		原邮箱不可用: "Can't use old email?",
		使用其他方法验证: "Try another method",
		原手机号验证: "Verify old number",
		原邮箱验证: "Verify old Email",
		数据同步: "Sync Data",
		删除该设备: "Remove Device",
		添加设备: "Add Device",
		未选择: "Not Selected",
		当前已经绑定该设备: "Device already bound",
		请选择一个设备: "Select a device",
		头像: "Photo",
		会员名: "Username",
		身体基础信息: "Basic Metrics",
		健康档案: "Health Profile",
		未登录: "Not Logged In",
		传统血压计使用指南: "Upper Arm Blood Pressure monitor Instructions",
		传统血压计问题解答: 'Upper Arm Blood Pressure Q&A',
		体脂秤使用指南: 'Body Scale Instructions',
		体脂秤问题解答: 'Body Scale Q&A',
		想和您共享健康数据: "is requesting to share his/her health data with you",
		接受: "Accept",
		已与您共享健康数据: "shares his/her health data with you",
		请输入新的会员名: "New username",
		会员名修改: "Change Username",
		暂无消息: "No notifications",
		我的健康档案: "My Health Records",
		单位设置: "Unit Settings",
		设备管理: "Devices",
		提醒设置: "Reminders",
		警报: 'Alarms',
		低压报警: 'Low-voltage alarm',
		高压报警: 'High voltage alarm',

		警报使用提示1: 'Alarms will be triggered if any measurements fall outside the normal ranges outlined above.',
		警报使用提示2: 'Use the checkbox next to each user to enable or disable alarm notifications for that individual.',
		用户: 'User',
		用户1: 'Myself',
		通知标题: 'JakobLife Alrams',
		警报内容: 'Alert content',
		测量通知: 'Measurement notification',

		舒张压有未录入: 'Diastolic pressure was not recorded',
		收缩压有未录入: 'Systolic pressure is not recorded',
		脉搏有未录入: 'No pulse recorded',
		血氧有未录入: 'Blood oxygen has not been recorded',
		血氧最大值不能超过: 'Maximum blood oxygen must not exceed 100',

		安全中心: "Security",
		我的: "Profile",
		暂无数据: "No data",
		时间: "Time",
		重复: "Repeat",
		标签: "Label",
		震动: "Vibration",
		稍后提醒: "Remind Later",
		保存: "Save",
		选择重复时间: "Repeat Schedule",
		请填写标签: "Label name",
		请选择铃声: "Alert tone",
		保存成功: "Saved!",
		未设置会员名: 'No username',
		永不: "Never",
		设置登录密码: "Set Password",
		第三方账号绑定: "Social Accounts",
		微信: "WeChat",
		退出登录: "Log Out",
		款血压计绑定教程: "4G BP Monitor Guide",
		款血压计绑定不了: "4G BP Monitor Issues",
		WIFI款血压计绑定教程: "WiFi/BT BP Monitor Guide",
		WIFI款血压计绑定不了: "WiFi/BT BP Monitor Issues",
		网络问题2: "TSB-617B-T, JL-BP67G, JL-BP68G use 4G",
		网络问题3: "JL-BP67W, JL-BP68W use WiFi",
		公斤: 'lb',
		斤: 'Kg',
		他人与我共享: "Shared With Me",
		暂无用户与您共享健康数据: "No shared data yet",
		健康共享: "Health Sharing",
		掌握权在您手中: "You're in Control",
		安全共享您的健康数据: "Safely share health data with designated family members.",
		图标汇总和通知: "Alerts & Reports",
		您共享的数据将在其: "Share the detailed report with family members and notify them in the event of any identified risks.",
		私密且安全: "Private & Secure",
		仅分享每个主题的摘要: "Summary-level sharing only\n(encrypted, revocable)",
		共享对象: "Recipients must have JakobLife accounts",
		您正在与: "Sharing with:",
		共享以下健康数据: "Shared Data:",
		正在与您共享以下健康数据: "Shared with You:",
		注本页面显示均为最近测量数据: "Note: Recent measurements",
		编辑: "Edit",
		共享: "Share",
		趋势: "Trends",
		您将与: "Share with:",
		您始终可以更改共享或停止共享: "You can modify/stop sharing anytime. Stopping removes your data from their device.",
		全选: "Select All",
		请选择要共享的数据: "Data to share",
		取消共享: "Revoke Access",
		请搜索会员名或手机号: "Search by username/phone",
		此账号异常登录: "Suspicious login detected",
		删除记录: 'Delete Records',
		动态血压监测报告仅支持导出单日数据: "ABPM: Single-day export only",
		导出的数据时间不能超过一年: 'Max 1-year export',
		确保每天摄入足够的水: 'Stay hydrated to avoid thirst/hunger confusion',
		增重速度: 'Weight Gain Rate',
		您的身体数据均为正常请继续保持: 'All metrics normal - keep it up!',
		分钟240: '240 mins',
		分钟30: '30 mins',
		分钟60: '60 mins',
		分钟90: '90 mins',
		分钟120: '120 mins',
		小时以上2: '2+ hours',
		请选择报告日期: "Report Date",
		请选择起床时间: "Wake-up Time",
		请选择就寝时间: "Bedtime",
		请选择是否午休: "Take Nap?",
		请选择午休时长: "Nap Duration",
		请选择是否服用药物: "Taking medications",
		请选择当前用药: "Current Meds",
		请选择工作是否倒班: "Shift Work?",
		请注意: "*Note: This report is for reference only. Consult medical professionals for advice and treatment.",
		检测设备: "Device",
		日期: "Date",
		次: "times",
		动态血压趋势图: "ABPM Trend Chart",
		动态血压监测统计表: "ABPM Statistics",
		动态血压监测相关图: "ABPM Correlation (24h)",
		动态血压监测数据统计: "ABPM Data Summary",
		白天清醒时段: "Daytime (Awake)",
		夜间睡眠时段: "Nighttime (Asleep)",
		起床后清晨时段: 'Early Morning Hours',
		睡眠时段测量数据: "Sleep Period Data",
		有效数据个数: "Valid Readings (%)",
		均值: "Mean",
		标准差: "SD",
		最大值: "Max",
		中位数: "Median",
		最小值: "Min",
		变异系数: "CV",
		有效测量次数: "Valid Measurements",
		总计监测时间: "Total Duration",
		有效监测时间: "Valid Duration",
		血压负荷: "BP Load",
		夜间血压下降率: "Nocturnal Dip",
		血压晨峰: "Morning Surge",
		动脉硬化指数: "Arterial Stiffness",
		盐敏感可能性: "Salt Sensitivity",
		平均动脉压: "MAP",
		告知1: "DBP=5.94+0.60×SBP",
		告知2: "SBP-DBP correlation: r=0.84 (strong positive)",
		手动输入数据: "Manual Entry",
		无效数据: "Invalid Data",
		是否下载动态血压监测报告: "Download ABPM Report?",
		血压分析和建议: "Analysis & Recommendations",
		分析: "Findings:",
		分析1: 'Nocturnal systolic blood pressure dip: Reverse-dipper pattern',
		分析2: 'Nocturnal systolic blood pressure dip: Non-dipper pattern',
		分析3: 'Nocturnal systolic blood pressure dip: Extreme-dipper pattern',
		分析4: 'Nocturnal systolic blood pressure dip: Dipper pattern',
		分析5: 'Abnormal 24-hour systolic blood pressure load',
		分析6: 'Abnormal morning surge in blood pressure',
		分析7: 'Increased risk of arteriosclerosis',
		分析777: "1. Definition and Normal Range of the Arterial Sclerosis Index The arterial sclerosis index (AI) is an indicator used to assess the degree of arteriosclerosis by calculating the ratio of total cholesterol (TC) to high-density lipoprotein cholesterol (HDL-C) in the blood. Under normal conditions, the AI should be less than 4. An index greater than 4 suggests a higher degree of arteriosclerosis and may increase the risk of related diseases./n2. Specific Health Risks An elevated arterial sclerosis index may lead to the following health problems:/n* Cardiovascular Diseases: Conditions such as coronary artery disease, angina pectoris, and myocardial infarction. When arteriosclerosis occurs in the coronary arteries of the heart, it can cause narrowing or blockage of the vessels, leading to insufficient blood supply to the myocardium and potentially life-threatening events./n* Cerebrovascular Diseases: Such as cerebral infarction and stroke. If arteriosclerosis affects the blood vessels in the brain, it can cause insufficient cerebral blood supply and result in a stroke./n* Renal Dysfunction: Hardening of the renal arteries may lead to a decline in kidney function and, in severe cases, renal failure./n* Fundus Lesions: Arteriosclerosis in the retinal blood vessels can impair vision and lead to retinal diseases./n* Other Complications: Such as peripheral artery disease, which can cause limb pain, numbness, and even gangrene in severe cases./n3. Causes of Increased Health Risks An elevated arterial sclerosis index can be caused by:/n* Unhealthy Lifestyle Habits: Such as a long-term high-fat diet, lack of physical activity, smoking, and excessive alcohol consumption./n* Underlying Medical Conditions: Including hypertension, hypercholesterolemia, and diabetes, which accelerate the progression of arteriosclerosis./n* Genetic Factors: Some individuals may be genetically predisposed to lipid metabolism disorders, leading to a higher arterial sclerosis index./n4. Prevention and Management Recommendations To address an elevated arterial sclerosis index, consider the following measures:/n* Adjust Your Diet: Reduce intake of high-fat and high-cholesterol foods. Increase consumption of foods rich in dietary fiber (such as vegetables, fruits, and whole grains), and include moderate amounts of unsaturated fats (such as those from fish and nuts)./n* Engage in Regular Physical Activity: Perform at least 150 minutes of moderate-intensity aerobic exercise per week, such as brisk walking, swimming, or cycling, to promote circulation and metabolism./n* Quit Smoking and Limit Alcohol Intake: Quitting smoking helps reduce vascular endothelial damage, while limiting alcohol supports blood pressure and lipid control./n* Maintain a Healthy Weight: Keep your body weight within a healthy range to avoid being overweight or obese./n* Undergo Regular Health Checkups: Monitor key indicators such as blood pressure, blood lipids, and blood glucose. Adjust lifestyle or begin medical treatment as needed./n* Medication: Under a doctor's guidance, take lipid-lowering medications (e.g., statins), antiplatelet agents (e.g., aspirin), and other relevant treatments to slow the progression of arteriosclerosis./n5. Summary An elevated arterial sclerosis index is an important risk factor for cardiovascular diseases and other related health issues. By adopting a healthy lifestyle, undergoing regular health checkups, and receiving appropriate medical interventions, you can effectively reduce these risks and protect your vascular health. If your index is found to be elevated, it is recommended to seek medical advice promptly to develop a personalized treatment plan.",
		分析8: 'Abnormal daytime systolic blood pressure',
		分析9: 'Insufficient valid measurements over 24 hours',
		分析10: 'Insufficient valid measurements during daytime period',
		分析a: 'Insufficient valid measurements during nighttime period',
		分析81: 'Abnormal daytime diastolic blood pressure',
		分析82: 'Abnormal daytime blood pressure',
		分析83: 'Abnormal nighttime systolic blood pressure',
		分析84: 'Abnormal nighttime diastolic blood pressure',
		分析85: 'Abnormal nighttime blood pressure',
		分析86: 'Abnormal morning systolic blood pressure',
		分析87: 'Abnormal morning diastolic blood pressure',
		分析88: 'Abnormal morning blood pressure',
		分析91: 'Abnormal 24-hour blood pressure',
		分析101: 'Abnormal 24-hour systolic blood pressure',
		分析aa: 'Abnormal 24-hour diastolic blood pressure',
		分析11: 'Nocturnal diastolic blood pressure dip: Reverse-dipper pattern',
		分析22: 'Nocturnal diastolic blood pressure dip: Non-dipper pattern',
		分析33: 'Nocturnal diastolic blood pressure dip: Extreme-dipper pattern',
		分析44: 'Nocturnal diastolic blood pressure dip: Dipper pattern',
		分析52: 'Abnormal daytime systolic blood pressure load',
		分析53: 'Abnormal nighttime systolic blood pressure load',
		分析54: 'Abnormal morning systolic blood pressure load',
		分析55: 'Abnormal 24-hour diastolic blood pressure load',
		分析56: 'Abnormal daytime diastolic blood pressure load',
		分析57: 'Abnormal nighttime diastolic blood pressure load',
		分析58: 'Abnormal morning diastolic blood pressure load',
		建议: "Suggestions:",
		建议1: '1. Highest Risk Type: Indicates sustained sympathetic nervous system activity at night, leading to increased cardiac load.\n2. Significantly increased risk of ischemic stroke, heart failure, and sudden death.\n3. Common in high-risk populations (e.g., insomnia, OSA, Alzheimer’s disease, Parkinson’s disease, advanced diabetes, etc.).\n4.An independent risk factor strongly associated with recurrent stroke and mortality.',
		建议2: '1. Hypertension-related target organ damage: Left ventricular hypertrophy, renal impairment, atherosclerosis.\n2. Increased risk of cardiovascular and cerebrovascular events: such as stroke and myocardial infarction.\n3. Common in the following groups:\n - Elderly people;\n- Patients with diabetes;\n- Sleep-disordered breathing (e.g., OSA);\n- Chronic kidney disease patients.\n4. Non-dipper hypertensive patients have a 2–3 times higher incidence of cardiovascular and cerebrovascular events compared to dipper types.',
		建议3: '1. Higher risk, particularly for insufficient cerebral perfusion.\n2. Excessively low nighttime blood pressure may lead to cerebral ischemia, elderly falls, morning strokes, etc.\n3. Common in patients on long-term antihypertensive therapy, especially those with improper dosage or medication timing.',
		建议4: '1. Indicates a normal nocturnal decrease in sympathetic activity, reflecting healthy vascular regulation.\n2. Represents a healthy circadian blood pressure rhythm with the lowest cardiovascular risk.',
		建议5: '1. Significantly elevated risk of cardiovascular and cerebrovascular events.\n2. Increased risk of target organ damage.\n3. Early risk of atherosclerosis.\n4. Early damage in children and adolescents.\n5. Predicts masked hypertension and white coat hypertension.',
		建议6: 'Patients with elevated morning blood pressure have a significantly increased risk of cardiovascular and cerebrovascular events.\nIf morning blood pressure is poorly controlled, the risk of serious complications such as angina, myocardial infarction, and stroke increases sharply.',
		建议7: 'Elevated risk of:\n- Coronary heart disease (myocardial infarction, angina pectoris);\n- Stroke (ischemic cerebral infarction);\n- Peripheral arterial disease (PAD).',
		建议8: 'At risk of hypertension',
		建议9: 'Increase the number of 24-hour measurements',
		建议10: 'Increase the number of daytime measurements',
		建议11: 'Increase the number of nighttime measurements',

		您的身体健康暂无分析数据: 'There is no analysis data on your physical health for the time being',

		序号: "No.",
		正常高值血压: 'Elevated BP',
		创建我的帐户: 'Create my account',
		请确认密码: 'Confirm Password',
		注册账号已存在: 'Account already exists',
		成功: 'success',
		请输入邮箱: 'enter your email',
		绑定邮箱: 'Link Email',
		绑定邮箱1: 'Linked Email',
		厘米: "inch",
		请输入会员名或邮箱: 'Username/Email',
		监测时间: 'Monitoring time',
		监测时间在1天之内: "≤1 day",
		监测时间在2天之内: "≤2 days",
		监测时间在3天之内: "≤3 days",
		监测时间在4天之内: "≤4 days",
		监测时间在5天之内: "≤5 days",
		监测时间在6天之内: "≤6 days",
		监测时间在当周之内: "≤1 week",
		监测时间在前2周之内: "≤2 week",
		监测时间在前3周之内: "≤3 weeks",
		监测时间在当月之内: "≤1 month",
		监测时间在前2月之内: "≤2 months",
		监测时间在前3月之内: "≤3 months",
		请选择监测时间: 'Monitoring time',
		失败: 'Failed',
		软件更新: 'software update',
		请您阅读并同意注销协议: 'Agree to delete',
		注销提示: 'Warning',
		请确认是否注销JakobLife账号: 'Delete account?',
		账户不存在或密码错误: 'Account does not exist/Incorrect password',
		设备: 'Devices',
		提示: 'Reminder',
		确认移除此设备: 'Confirm to remove this device ',
		确认移除此设备1: 'If you connected Classic Bluetooth during the pairing process, please go to your phone’s Bluetooth settings and manually “Forget the device.”',
		确认移除此设备2: 'During the unbinding process, please keep upper arm BP’s screen active ',
		版本更新1: 'Version',
		版本更新2: ' is ready for update',
		已经是最新版本1: 'Version ',
		已经是最新版本2: 'This version is the latest version',
		当前下载进度: 'Current download progress',
		当前蓝牙未开启是否去设置打开: 'Bluetooth is currently off. Go to settings to enable it',
		数据不存在: 'Data does not exist',
		血压手表使用指南: 'Blood Pressure Watch Instructions',
		血压手表问题解答: 'Blood Pressure Watch Q&A',
		连接超时: 'timeout',
		此用户不存在: 'This user doesn’t exist',
		您已向: 'You have sent',
		发出共享健康数据邀请: 'Send an invitation to share health data',
		搜索: 'Search',
		血压分类: 'Blood pressure classification',
		根据WHOISH的血压分类2020年修订版: 'Blood pressure classification according to WHO/ISH (2020 revision)',
		和或: 'and/or',
		血压范围: 'Blood pressure ranges',
		血压类别: 'Blood pressure category',
		生成健康报告: 'Generate a health report',
		血压水平偏低: 'Low blood pressure',
		血压水平正常: 'Normal blood pressure level',
		血压水平偏高: 'High blood pressure',
		三级高血压: 'Tertiary hypertension',
		该邮箱已被绑定: 'This email is linked to a different account',
		该手机号已被绑定: "This phone is linked to a different account",
		选中的设备与扫码设备不匹配: 'The selected device doesn’t match the scanning code',
		至少选择一个选项: 'Select at least one option',
		设置新的正常范围: 'Set New Normal Ranges',
		设定成功: 'Set successfully',
		这个类别没有任何连接设备: 'This category doesn’t have any linked devices',
		体温: 'Body Temperature',
		压力: 'Stress',
		血压计注意事项: '“Please remain on the Home screen and keep your phone screen active while measuring blood pressure with Upper Arm BP monitor. This ensures the test is being performed by you and not someone else.”',
		体脂秤注意事项: 'Please ensure your phone screen remains active during body scale measurements, as data may not sync correctly with Bluetooth broadcast devices if the screen is off.  Other Jakoblife devices support data synchronization even when the screen is off.',
		手表注意事项: 'The watch uses low-power Bluetooth to extend battery life.  In this mode, it is unable to receive calls.If you would like to receive calls, please enable Classic Bluetooth on your watch.  Then, manually connect the watch from your phone’s Bluetooth settings.  The device will appear as BPW1.',
		网络连接异常: 'No internet connections, data will not be synchronized with the phone and the cloud',
		短信验证成功: 'success',
		邮箱验证成功: 'success',
		不知道设备型号: "Don't know the device model?",
		心血管: 'Cardiovascular',
		情绪: 'Mental',
		运动: 'Exercises',
		自动血压监测设置: 'Auto blood pressure monitoring setting',
		开始时间: 'Start time',
		结束时间: 'End time',
		设置自动血压监测: 'Set auto blood pressure monitoring',
		间隔时间: 'Interval time',
		关闭自动监控: 'Turn off auto monitoring',
		关闭成功: 'Shutdown success',
		打印: 'Print',
		去设置: 'go to setting',
		删除: 'Delete',
		容易: 'Easy',
		低压: 'Low pressure',
		适度的压力: 'Moderate pressure',
		高度的压力: 'High pressure',
		跳转设置: 'Jump Settings',
		是否跳转到蓝牙设置页面: 'Go to Bluetooth Settings?',
		手动选择: 'Scan available Bluetooth Devices ',
		扫码绑定: 'Scan bar code',
		BMI: 'BMI',
		此为血压计数据生成的报告不准确: 'This is a report generated from the blood pressure monitor data and is inaccurate',
		显示结果弹窗: 'The results indicate that your blood pressure may be elevated. We recommend monitoring your blood pressure at least once daily.',
		提示检测到血压偏高: 'Notice: Elevated Blood Pressure Detected Our records indicate that your blood pressure has been elevated at least once daily for more than three consecutive days.We recommend using our blood pressure monitoring smartwatch for continuous tracking to help improve health outcomes.If you are not currently taking medication for high blood pressure, we advise consulting your physician to discuss potential treatment options.If you are already on medication, please consult your doctor to evaluate whether adjustments to the dosage or timing are needed.Continuous monitoring with our smartwatch may help identify peak times of high blood pressure, enabling more effective medication timing.',
		提示检测到血压偏高1: 'Notice: Elevated Blood Pressure Detected Our records indicate that your blood pressure has been elevated at least once daily for more than three consecutive days.If you are not currently taking medication for high blood pressure, we advise consulting your physician to discuss potential treatment options.If you are already on medication, please consult your doctor to evaluate whether adjustments to the dosage or timing are needed.Continuous monitoring with our smartwatch may help identify peak times of high blood pressure, enabling more effective medication timing.',
		收起: 'Hide',
		展开更多: 'Details',
	}
}