#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef DCLOUDUTSEXTAPI_SWIFT_H
#define DCLOUDUTSEXTAPI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import DCloudUTSFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DCloudUTSExtAPI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS_NAMED("AppBaseInfoDeviceUtil")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoAppBaseInfoDeviceUtil : NSObject
+ (NSString * _Nonnull)getAppID SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostTheme SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostLanguage SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getHostPackageName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppVersionCode SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppWgtVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOsLanguage SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOsLanguageNormal SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getAppInnerVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getBundleId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getSignature SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class UTSSDKModulesDCloudUniChooseMediaChooseMediaOptions;
@class UIImagePickerController;

SWIFT_CLASS_NAMED("ChooseMediaImagePickerManager")
@interface UTSSDKModulesDCloudUniChooseMediaChooseMediaImagePickerManager : NSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (nonnull instancetype)init:(UTSSDKModulesDCloudUniChooseMediaChooseMediaOptions * _Nonnull)options OBJC_DESIGNATED_INITIALIZER;
- (void)chooseMediaWithCamera;
- (void)chooseMediaWithAlbum;
- (NSArray<NSString *> * _Nonnull)getMediaTypes:(NSArray<NSString *> * _Nullable)types SWIFT_WARN_UNUSED_RESULT;
- (void)dismiss:(UIImagePickerController * _Nonnull)picker;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
@class UTSSDKModulesDCloudUniChooseMediaChooseMediaSuccess;
@class UTSJSONObject;

SWIFT_CLASS_NAMED("ChooseMediaOptions")
@interface UTSSDKModulesDCloudUniChooseMediaChooseMediaOptions : NSObject
@property (nonatomic, copy) NSString * _Nullable pageOrientation;
@property (nonatomic, strong) NSNumber * _Nullable count;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable mediaType;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable sourceType;
@property (nonatomic, strong) NSNumber * _Nullable maxDuration;
@property (nonatomic, copy) NSString * _Nullable camera;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniChooseMediaChooseMediaSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSCallback;

SWIFT_CLASS_NAMED("ChooseMediaOptionsJSONObject")
@interface UTSSDKModulesDCloudUniChooseMediaChooseMediaOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Nullable pageOrientation;
@property (nonatomic, strong) NSNumber * _Nullable count;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable mediaType;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable sourceType;
@property (nonatomic, strong) NSNumber * _Nullable maxDuration;
@property (nonatomic, copy) NSString * _Nullable camera;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PHPickerViewController;

SWIFT_CLASS_NAMED("ChooseMediaPHPickerManager") SWIFT_AVAILABILITY(ios,introduced=14.0)
@interface UTSSDKModulesDCloudUniChooseMediaChooseMediaPHPickerManager : NSObject
- (nonnull instancetype)init:(UTSSDKModulesDCloudUniChooseMediaChooseMediaOptions * _Nonnull)options OBJC_DESIGNATED_INITIALIZER;
- (void)chooseMediaWithAlbum;
- (NSString * _Nonnull)getFileType:(NSArray<NSString *> * _Nonnull)types SWIFT_WARN_UNUSED_RESULT;
- (void)dismiss:(PHPickerViewController * _Nonnull)picker;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UTSSDKModulesDCloudUniChooseMediaChooseMediaTempFile;

SWIFT_CLASS_NAMED("ChooseMediaSuccess")
@interface UTSSDKModulesDCloudUniChooseMediaChooseMediaSuccess : NSObject
@property (nonatomic, copy) NSArray<UTSSDKModulesDCloudUniChooseMediaChooseMediaTempFile *> * _Null_unspecified tempFiles;
@property (nonatomic, copy) NSString * _Null_unspecified type;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ChooseMediaTempFile")
@interface UTSSDKModulesDCloudUniChooseMediaChooseMediaTempFile : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified tempFilePath;
@property (nonatomic, copy) NSString * _Null_unspecified fileType;
@property (nonatomic, strong) NSNumber * _Null_unspecified size;
@property (nonatomic, strong) NSNumber * _Nullable byteSize;
@property (nonatomic, strong) NSNumber * _Nullable duration;
@property (nonatomic, strong) NSNumber * _Nullable height;
@property (nonatomic, strong) NSNumber * _Nullable width;
@property (nonatomic, copy) NSString * _Nullable thumbTempFilePath;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class NSURL;

SWIFT_CLASS_NAMED("ChooseMediaUtil")
@interface UTSSDKModulesDCloudUniChooseMediaChooseMediaUtil : NSObject
+ (NSString * _Nonnull)createFilePath:(NSString * _Nonnull)fileName SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)saveImage:(UIImage * _Nonnull)image :(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)getFristFrameWithVideo:(NSURL * _Nonnull)reassignedUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary<NSString *, id> * _Nonnull)getVideoInfo:(NSURL * _Nonnull)reassignedUrl SWIFT_WARN_UNUSED_RESULT;
+ (UTSSDKModulesDCloudUniChooseMediaChooseMediaTempFile * _Nullable)getTempFileWithImage:(UIImage * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
+ (UTSSDKModulesDCloudUniChooseMediaChooseMediaTempFile * _Nullable)getTempFileWithVideo:(NSURL * _Nonnull)mediaUrl SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageClearStorageSuccess;
@class UniError;

SWIFT_CLASS_NAMED("ClearStorageOptions")
@interface UTSSDKModulesDCloudUniStorageClearStorageOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageClearStorageSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ClearStorageOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageClearStorageOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ClearStorageSuccess")
@interface UTSSDKModulesDCloudUniStorageClearStorageSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;
@protocol UIViewControllerTransitionCoordinator;
@class NSBundle;

SWIFT_CLASS("_TtC15DCloudUTSExtAPI23DCActionSheetController")
@interface DCActionSheetController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@class UITableView;
@class NSIndexPath;
@class UITableViewCell;
@class UIView;

@interface DCActionSheetController (SWIFT_EXTENSION(DCloudUTSExtAPI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC15DCloudUTSExtAPI13DCAlertAction")
@interface DCAlertAction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15DCloudUTSExtAPI19DCAlertActionButton")
@interface DCAlertActionButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// /////////////////////////// DCAlertViewController /////////////////////
SWIFT_CLASS("_TtC15DCloudUTSExtAPI21DCAlertViewController")
@interface DCAlertViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)loadView;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@protocol UIViewControllerAnimatedTransitioning;

@interface DCAlertViewController (SWIFT_EXTENSION(DCloudUTSExtAPI)) <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC15DCloudUTSExtAPI14DCRIButtonItem")
@interface DCRIButtonItem : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DeviceUtil")
@interface UTSSDKModulesDCloudUniGetDeviceInfoDeviceUtil : NSObject
+ (BOOL)isPad SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOSVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getLan SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOrientation SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasRootPrivilege SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;
@class NSURLSessionDownloadTask;
@class NSURLSessionTask;

SWIFT_CLASS_NAMED("DownloadController")
@interface UTSSDKModulesDCloudUniNetworkDownloadController : NSObject <NSURLSessionDownloadDelegate>
+ (UTSSDKModulesDCloudUniNetworkDownloadController * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didWriteData:(int64_t)bytesWritten totalBytesWritten:(int64_t)totalBytesWritten totalBytesExpectedToWrite:(int64_t)totalBytesExpectedToWrite;
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didFinishDownloadingToURL:(NSURL * _Nonnull)location;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniNetworkDownloadFileSuccess;

SWIFT_CLASS_NAMED("DownloadFileOptions")
@interface UTSSDKModulesDCloudUniNetworkDownloadFileOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified url;
@property (nonatomic, strong) UTSJSONObject * _Nullable header;
@property (nonatomic, copy) NSString * _Nullable filePath;
@property (nonatomic, strong) NSNumber * _Nullable timeout;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniNetworkDownloadFileSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DownloadFileOptionsJSONObject")
@interface UTSSDKModulesDCloudUniNetworkDownloadFileOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified url;
@property (nonatomic, strong) UTSJSONObject * _Nullable header;
@property (nonatomic, copy) NSString * _Nullable filePath;
@property (nonatomic, strong) NSNumber * _Nullable timeout;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DownloadFileSuccess")
@interface UTSSDKModulesDCloudUniNetworkDownloadFileSuccess : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified tempFilePath;
@property (nonatomic, strong) NSNumber * _Null_unspecified statusCode;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniNetworkOnProgressDownloadResult;
@class NSHTTPURLResponse;

SWIFT_CLASS_NAMED("NetworkDownloadFileListener")
@interface UTSSDKModulesDCloudUniNetworkNetworkDownloadFileListener : NSObject
@property (nonatomic, weak) id _Nullable task;
@property (nonatomic, strong) UTSSDKModulesDCloudUniNetworkDownloadFileOptions * _Nullable options;
- (void)onProgress:(UTSSDKModulesDCloudUniNetworkOnProgressDownloadResult * _Nonnull)progressUpdate;
- (void)onFinished:(NSHTTPURLResponse * _Nonnull)response :(NSString * _Nonnull)filePath;
- (void)onFail:(NSError * _Nonnull)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DownloadNetworkListener")
@interface UTSSDKModulesDCloudUniNetworkDownloadNetworkListener : UTSSDKModulesDCloudUniNetworkNetworkDownloadFileListener
@property (nonatomic, strong) UTSSDKModulesDCloudUniNetworkDownloadFileOptions * _Nullable options;
@property (nonatomic, weak) id _Nullable task;
- (nonnull instancetype)init:(UTSSDKModulesDCloudUniNetworkDownloadFileOptions * _Nonnull)options OBJC_DESIGNATED_INITIALIZER;
- (void)onProgress:(UTSSDKModulesDCloudUniNetworkOnProgressDownloadResult * _Nonnull)progressUpdate;
- (void)onFinished:(NSHTTPURLResponse * _Nonnull)response :(NSString * _Nonnull)filePath;
- (void)onFail:(NSError * _Nonnull)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DownloadTaskByJsProxy")
@interface UTSSDKModulesDCloudUniNetworkDownloadTaskByJsProxy : NSObject
- (void)abortByJs;
- (void)onProgressUpdateByJs:(UTSCallback * _Nonnull)callback;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UTSSDKModulesDCloudUniExitExitSuccess;

SWIFT_CLASS_NAMED("ExitOptions")
@interface UTSSDKModulesDCloudUniExitExitOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniExitExitSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ExitOptionsJSONObject")
@interface UTSSDKModulesDCloudUniExitExitOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ExitSuccess")
@interface UTSSDKModulesDCloudUniExitExitSuccess : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified errMsg;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetAppBaseInfoOptions")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoOptions : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified filter;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetAppBaseInfoOptionsJSONObject")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoOptionsJSONObject : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified filter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetAppBaseInfoResult")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoResult : NSObject
@property (nonatomic, copy) NSString * _Nullable appId;
@property (nonatomic, copy) NSString * _Nullable appName;
@property (nonatomic, copy) NSString * _Nullable appVersion;
@property (nonatomic, copy) NSString * _Nullable appVersionCode;
@property (nonatomic, copy) NSString * _Nullable appLanguage;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, copy) NSString * _Nullable appWgtVersion;
@property (nonatomic, copy) NSString * _Nullable hostLanguage;
@property (nonatomic, copy) NSString * _Nullable hostVersion;
@property (nonatomic, copy) NSString * _Nullable hostName;
@property (nonatomic, copy) NSString * _Nullable hostPackageName;
@property (nonatomic, copy) NSString * _Nullable hostSDKVersion;
@property (nonatomic, copy) NSString * _Nullable hostTheme;
@property (nonatomic) BOOL isUniAppX;
@property (nonatomic, copy) NSString * _Nullable uniCompileVersion;
@property (nonatomic, copy) NSString * _Nullable uniCompilerVersion;
@property (nonatomic, copy) NSString * _Nullable uniPlatform;
@property (nonatomic, copy) NSString * _Nullable uniRuntimeVersion;
@property (nonatomic, strong) NSNumber * _Nullable uniCompileVersionCode;
@property (nonatomic, strong) NSNumber * _Nullable uniCompilerVersionCode;
@property (nonatomic, strong) NSNumber * _Nullable uniRuntimeVersionCode;
@property (nonatomic, copy) NSString * _Nullable packageName;
@property (nonatomic, copy) NSString * _Nullable bundleName;
@property (nonatomic, copy) NSString * _Nullable bundleId;
@property (nonatomic, copy) NSString * _Nullable signature;
@property (nonatomic, copy) NSString * _Nullable appTheme;
@property (nonatomic, copy) NSString * _Nullable channel;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetDeviceInfoOptions")
@interface UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoOptions : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified filter;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetDeviceInfoOptionsJSONObject")
@interface UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoOptionsJSONObject : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified filter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetDeviceInfoResult")
@interface UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoResult : NSObject
@property (nonatomic, copy) NSString * _Nullable brand;
@property (nonatomic, copy) NSString * _Nullable deviceBrand;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable model;
@property (nonatomic, copy) NSString * _Nullable deviceModel;
@property (nonatomic, copy) NSString * _Nullable deviceType;
@property (nonatomic, copy) NSString * _Nullable deviceOrientation;
@property (nonatomic, strong) NSNumber * _Nullable devicePixelRatio;
@property (nonatomic, copy) NSString * _Nullable system;
@property (nonatomic, copy) NSString * _Nullable platform;
@property (nonatomic) BOOL isRoot;
@property (nonatomic) BOOL isSimulator;
@property (nonatomic) BOOL isUSBDebugging;
@property (nonatomic, copy) NSString * _Nullable osName;
@property (nonatomic, copy) NSString * _Nullable osVersion;
@property (nonatomic, copy) NSString * _Nullable osLanguage;
@property (nonatomic, copy) NSString * _Nullable osTheme;
@property (nonatomic, strong) NSNumber * _Nullable osAndroidAPILevel;
@property (nonatomic, strong) NSNumber * _Nullable osHarmonySDKAPIVersion;
@property (nonatomic, copy) NSString * _Nullable osHarmonyDisplayVersion;
@property (nonatomic, copy) NSString * _Nullable romName;
@property (nonatomic, copy) NSString * _Nullable romVersion;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniPrivacyGetPrivacySettingSuccessResult;

SWIFT_CLASS_NAMED("GetPrivacySettingOptions")
@interface UTSSDKModulesDCloudUniPrivacyGetPrivacySettingOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniPrivacyGetPrivacySettingSuccessResult * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(id _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetPrivacySettingOptionsJSONObject")
@interface UTSSDKModulesDCloudUniPrivacyGetPrivacySettingOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetPrivacySettingSuccessResult")
@interface UTSSDKModulesDCloudUniPrivacyGetPrivacySettingSuccessResult : NSObject
@property (nonatomic) BOOL needAuthorization;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageGetStorageInfoSuccess;

SWIFT_CLASS_NAMED("GetStorageInfoOptions")
@interface UTSSDKModulesDCloudUniStorageGetStorageInfoOptions : NSObject
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageGetStorageInfoSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetStorageInfoOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageGetStorageInfoOptionsJSONObject : NSObject
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetStorageInfoSuccess")
@interface UTSSDKModulesDCloudUniStorageGetStorageInfoSuccess : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified keys;
@property (nonatomic, strong) NSNumber * _Null_unspecified currentSize;
@property (nonatomic, strong) NSNumber * _Null_unspecified limitSize;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageGetStorageSuccess;

SWIFT_CLASS_NAMED("GetStorageOptions")
@interface UTSSDKModulesDCloudUniStorageGetStorageOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageGetStorageSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetStorageOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageGetStorageOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetStorageSuccess")
@interface UTSSDKModulesDCloudUniStorageGetStorageSuccess : NSObject
@property (nonatomic) id _Nullable data;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("GetSystemSettingResult")
@interface UTSSDKModulesDCloudUniGetSystemSettingGetSystemSettingResult : NSObject
@property (nonatomic) BOOL bluetoothEnabled;
@property (nonatomic, copy) NSString * _Nullable bluetoothError;
@property (nonatomic) BOOL locationEnabled;
@property (nonatomic) BOOL wifiEnabled;
@property (nonatomic, copy) NSString * _Nullable wifiError;
@property (nonatomic, copy) NSString * _Null_unspecified deviceOrientation;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DCloudUTSExtAPI7MCToast")
@interface MCToast : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


















SWIFT_CLASS("_TtC15DCloudUTSExtAPI13MCToastConfig")
@interface MCToastConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS_NAMED("NetworkDownloadTaskImpl")
@interface UTSSDKModulesDCloudUniNetworkNetworkDownloadTaskImpl : NSObject
- (nonnull instancetype)init:(NSURLSessionDownloadTask * _Nullable)task :(UTSSDKModulesDCloudUniNetworkNetworkDownloadFileListener * _Nonnull)listener OBJC_DESIGNATED_INITIALIZER;
- (void)abort;
- (void)onProgressUpdate:(void (^ _Nonnull)(UTSSDKModulesDCloudUniNetworkOnProgressDownloadResult * _Nonnull))option;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSessionDataTask;
@class NSURLResponse;
@class NSData;

SWIFT_CLASS_NAMED("NetworkManager")
@interface UTSSDKModulesDCloudUniNetworkNetworkManager : NSObject <NSURLSessionDataDelegate>
+ (UTSSDKModulesDCloudUniNetworkNetworkManager * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("NetworkRequestListener")
@interface UTSSDKModulesDCloudUniNetworkNetworkRequestListener : NSObject
@property (nonatomic, weak) id _Nullable task;
- (void)onStart;
- (void)onHeadersReceived:(NSNumber * _Nonnull)statusCode :(NSDictionary<NSString *, id> * _Nonnull)headers;
- (void)onDataReceived:(NSData * _Nonnull)data;
- (void)onFinished:(NSHTTPURLResponse * _Nonnull)response;
- (void)onFail:(NSError * _Nonnull)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniNetworkRequestTaskOnHeadersReceivedListenerResult;
@class UTSSDKModulesDCloudUniNetworkRequestTaskOnChunkReceivedListenerResult;

SWIFT_CLASS_NAMED("NetworkRequestTaskImpl")
@interface UTSSDKModulesDCloudUniNetworkNetworkRequestTaskImpl : NSObject
- (nonnull instancetype)init:(NSURLSessionDataTask * _Nullable)task OBJC_DESIGNATED_INITIALIZER;
- (void)abort;
- (NSNumber * _Nonnull)onHeadersReceived:(void (^ _Nonnull)(UTSSDKModulesDCloudUniNetworkRequestTaskOnHeadersReceivedListenerResult * _Nonnull))listener SWIFT_WARN_UNUSED_RESULT;
- (void)offHeadersReceived:(id _Nullable)listener;
- (NSNumber * _Nonnull)onChunkReceived:(void (^ _Nonnull)(UTSSDKModulesDCloudUniNetworkRequestTaskOnChunkReceivedListenerResult * _Nonnull))listener SWIFT_WARN_UNUSED_RESULT;
- (void)offChunkReceived:(id _Nullable)listener;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UTSSDKModulesDCloudUniNetworkOnProgressUpdateResult;

SWIFT_CLASS_NAMED("NetworkUploadFileListener")
@interface UTSSDKModulesDCloudUniNetworkNetworkUploadFileListener : NSObject
@property (nonatomic, weak) id _Nullable task;
- (void)onProgress:(UTSSDKModulesDCloudUniNetworkOnProgressUpdateResult * _Nonnull)progressUpdate;
- (void)onDataReceived:(NSData * _Nonnull)data;
- (void)onFinished:(NSHTTPURLResponse * _Nonnull)response;
- (void)onFail:(NSError * _Nonnull)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("NetworkUploadTaskImpl")
@interface UTSSDKModulesDCloudUniNetworkNetworkUploadTaskImpl : NSObject
- (nonnull instancetype)init:(NSURLSessionDataTask * _Nullable)task :(UTSSDKModulesDCloudUniNetworkNetworkUploadFileListener * _Nonnull)listener OBJC_DESIGNATED_INITIALIZER;
- (void)abort;
- (void)onProgressUpdate:(void (^ _Nonnull)(UTSSDKModulesDCloudUniNetworkOnProgressUpdateResult * _Nonnull))option;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("NetworkUtil")
@interface UTSSDKModulesDCloudUniNetworkNetworkUtil : NSObject
+ (UTSJSONObject * _Nonnull)convertHeaders:(NSDictionary<NSString *, id> * _Nullable)headers SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)parseCookie:(UTSJSONObject * _Nullable)header SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OnProgressDownloadResult")
@interface UTSSDKModulesDCloudUniNetworkOnProgressDownloadResult : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified progress;
@property (nonatomic, strong) NSNumber * _Null_unspecified totalBytesWritten;
@property (nonatomic, strong) NSNumber * _Null_unspecified totalBytesExpectedToWrite;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OnProgressUpdateResult")
@interface UTSSDKModulesDCloudUniNetworkOnProgressUpdateResult : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified progress;
@property (nonatomic, strong) NSNumber * _Null_unspecified totalBytesSent;
@property (nonatomic, strong) NSNumber * _Null_unspecified totalBytesExpectedToSend;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Popover")
@interface UTSSDKModulesDCloudUniPromptPopover : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified top;
@property (nonatomic, strong) NSNumber * _Null_unspecified left;
@property (nonatomic, strong) NSNumber * _Null_unspecified width;
@property (nonatomic, strong) NSNumber * _Null_unspecified height;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("PrivacyChangeResult")
@interface UTSSDKModulesDCloudUniPrivacyPrivacyChangeResult : NSObject
@property (nonatomic) BOOL needAuthorization;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageRemoveStorageSuccess;

SWIFT_CLASS_NAMED("RemoveStorageOptions")
@interface UTSSDKModulesDCloudUniStorageRemoveStorageOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageRemoveStorageSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("RemoveStorageOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageRemoveStorageOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("RemoveStorageSuccess")
@interface UTSSDKModulesDCloudUniStorageRemoveStorageSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("RequestOptionsJSONObject")
@interface UTSSDKModulesDCloudUniNetworkRequestOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified url;
@property (nonatomic) id _Nullable data;
@property (nonatomic, strong) UTSJSONObject * _Nullable header;
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, strong) NSNumber * _Nullable timeout;
@property (nonatomic, copy) NSString * _Nullable dataType;
@property (nonatomic, copy) NSString * _Nullable responseType;
@property (nonatomic) BOOL sslVerify;
@property (nonatomic) BOOL withCredentials;
@property (nonatomic) BOOL firstIpv4;
@property (nonatomic) BOOL enableChunked;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("RequestTaskByJsProxy")
@interface UTSSDKModulesDCloudUniNetworkRequestTaskByJsProxy : NSObject
- (void)abortByJs;
- (NSNumber * _Nonnull)onChunkReceivedByJs:(UTSCallback * _Nonnull)listener SWIFT_WARN_UNUSED_RESULT;
- (void)offChunkReceivedByJs:(id _Nullable)listener;
- (NSNumber * _Nonnull)onHeadersReceivedByJs:(UTSCallback * _Nonnull)listener SWIFT_WARN_UNUSED_RESULT;
- (void)offHeadersReceivedByJs:(id _Nullable)listener;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ArrayBuffer;

SWIFT_CLASS_NAMED("RequestTaskOnChunkReceivedListenerResult")
@interface UTSSDKModulesDCloudUniNetworkRequestTaskOnChunkReceivedListenerResult : NSObject
@property (nonatomic, strong) ArrayBuffer * _Null_unspecified data;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("RequestTaskOnHeadersReceivedListenerResult")
@interface UTSSDKModulesDCloudUniNetworkRequestTaskOnHeadersReceivedListenerResult : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified cookies;
@property (nonatomic, strong) UTSJSONObject * _Null_unspecified header;
@property (nonatomic, strong) NSNumber * _Null_unspecified statusCode;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniStorageSetStorageSuccess;

SWIFT_CLASS_NAMED("SetStorageOptions")
@interface UTSSDKModulesDCloudUniStorageSetStorageOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic) id _Null_unspecified data;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniStorageSetStorageSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable fail)(UniError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SetStorageOptionsJSONObject")
@interface UTSSDKModulesDCloudUniStorageSetStorageOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified key;
@property (nonatomic) id _Null_unspecified data;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SetStorageSuccess")
@interface UTSSDKModulesDCloudUniStorageSetStorageSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniPromptShowActionSheetSuccess;

SWIFT_CLASS_NAMED("ShowActionSheetOptions")
@interface UTSSDKModulesDCloudUniPromptShowActionSheetOptions : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable alertText;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified itemList;
@property (nonatomic, copy) NSString * _Nullable itemColor;
@property (nonatomic, strong) UTSSDKModulesDCloudUniPromptPopover * _Nullable popover;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniPromptShowActionSheetSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowActionSheetOptionsJSONObject")
@interface UTSSDKModulesDCloudUniPromptShowActionSheetOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable alertText;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified itemList;
@property (nonatomic, copy) NSString * _Nullable itemColor;
@property (nonatomic, strong) UTSSDKModulesDCloudUniPromptPopover * _Nullable popover;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowActionSheetSuccess")
@interface UTSSDKModulesDCloudUniPromptShowActionSheetSuccess : NSObject
@property (nonatomic, strong) NSNumber * _Null_unspecified tapIndex;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniPromptShowLoadingSuccess;

SWIFT_CLASS_NAMED("ShowLoadingOptions")
@interface UTSSDKModulesDCloudUniPromptShowLoadingOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic) BOOL mask;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniPromptShowLoadingSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowLoadingOptionsJSONObject")
@interface UTSSDKModulesDCloudUniPromptShowLoadingOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic) BOOL mask;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowLoadingSuccess")
@interface UTSSDKModulesDCloudUniPromptShowLoadingSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniPromptShowModalSuccess;

SWIFT_CLASS_NAMED("ShowModalOptions")
@interface UTSSDKModulesDCloudUniPromptShowModalOptions : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) BOOL showCancel;
@property (nonatomic, copy) NSString * _Nullable cancelText;
@property (nonatomic, copy) NSString * _Nullable cancelColor;
@property (nonatomic, copy) NSString * _Nullable confirmText;
@property (nonatomic, copy) NSString * _Nullable confirmColor;
@property (nonatomic) BOOL editable;
@property (nonatomic, copy) NSString * _Nullable placeholderText;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniPromptShowModalSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowModalOptionsJSONObject")
@interface UTSSDKModulesDCloudUniPromptShowModalOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) BOOL showCancel;
@property (nonatomic, copy) NSString * _Nullable cancelText;
@property (nonatomic, copy) NSString * _Nullable cancelColor;
@property (nonatomic, copy) NSString * _Nullable confirmText;
@property (nonatomic, copy) NSString * _Nullable confirmColor;
@property (nonatomic) BOOL editable;
@property (nonatomic, copy) NSString * _Nullable placeholderText;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowModalSuccess")
@interface UTSSDKModulesDCloudUniPromptShowModalSuccess : NSObject
@property (nonatomic) BOOL confirm;
@property (nonatomic) BOOL cancel;
@property (nonatomic, copy) NSString * _Nullable content;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniPromptShowToastSuccess;

SWIFT_CLASS_NAMED("ShowToastOptions")
@interface UTSSDKModulesDCloudUniPromptShowToastOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic) BOOL mask;
@property (nonatomic, strong) NSNumber * _Nullable duration;
@property (nonatomic, copy) NSString * _Nullable position;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniPromptShowToastSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowToastOptionsJSONObject")
@interface UTSSDKModulesDCloudUniPromptShowToastOptionsJSONObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic) BOOL mask;
@property (nonatomic, strong) NSNumber * _Nullable duration;
@property (nonatomic, copy) NSString * _Nullable position;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ShowToastSuccess")
@interface UTSSDKModulesDCloudUniPromptShowToastSuccess : NSObject
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("StatusCode")
@interface UTSSDKModulesDCloudUniNetworkStatusCode : NSObject
+ (NSString * _Nonnull)getStatus:(NSString * _Nonnull)code SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("StorageTool")
@interface UTSSDKModulesDCloudUniStorageStorageTool : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end













SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniChooseMediaIndexSwift")
@interface UTSSDKModulesDCloudUniChooseMediaIndexSwift : NSObject
+ (void)s_chooseMediaByJs:(UTSSDKModulesDCloudUniChooseMediaChooseMediaOptionsJSONObject * _Nonnull)options;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniExitIndexSwift")
@interface UTSSDKModulesDCloudUniExitIndexSwift : NSObject
+ (void)s_exitByJs:(UTSSDKModulesDCloudUniExitExitOptionsJSONObject * _Nullable)options;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetAppBaseInfoIndexSwift")
@interface UTSSDKModulesDCloudUniGetAppBaseInfoIndexSwift : NSObject
+ (UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoResult * _Nonnull)s_getAppBaseInfoByJs:(UTSSDKModulesDCloudUniGetAppBaseInfoGetAppBaseInfoOptionsJSONObject * _Nullable)options SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetDeviceInfoIndexSwift")
@interface UTSSDKModulesDCloudUniGetDeviceInfoIndexSwift : NSObject
+ (BOOL)s_isSimulatorByJs SWIFT_WARN_UNUSED_RESULT;
+ (UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoResult * _Nonnull)s_getDeviceInfoByJs:(UTSSDKModulesDCloudUniGetDeviceInfoGetDeviceInfoOptionsJSONObject * _Nullable)options SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniGetSystemSettingIndexSwift")
@interface UTSSDKModulesDCloudUniGetSystemSettingIndexSwift : NSObject
+ (UTSSDKModulesDCloudUniGetSystemSettingGetSystemSettingResult * _Nonnull)s_getSystemSettingByJs SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniNetworkUploadFileOptionsJSONObject;

SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniNetworkIndexSwift")
@interface UTSSDKModulesDCloudUniNetworkIndexSwift : NSObject
+ (NSInteger)s_requestByJs:(UTSSDKModulesDCloudUniNetworkRequestOptionsJSONObject * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
+ (NSInteger)s_uploadFileByJs:(UTSSDKModulesDCloudUniNetworkUploadFileOptionsJSONObject * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
+ (NSInteger)s_downloadFileByJs:(UTSSDKModulesDCloudUniNetworkDownloadFileOptionsJSONObject * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniPrivacyIndexSwift")
@interface UTSSDKModulesDCloudUniPrivacyIndexSwift : NSObject
+ (void)s_getPrivacySettingByJs:(UTSSDKModulesDCloudUniPrivacyGetPrivacySettingOptionsJSONObject * _Nonnull)options;
+ (void)s_resetPrivacyAuthorizationByJs;
+ (NSNumber * _Nonnull)s_onPrivacyAuthorizationChangeByJs:(UTSCallback * _Nonnull)callback SWIFT_WARN_UNUSED_RESULT;
+ (void)s_offPrivacyAuthorizationChangeByJs:(NSNumber * _Nonnull)id;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniPromptIndexSwift")
@interface UTSSDKModulesDCloudUniPromptIndexSwift : NSObject
+ (void)s_showToastByJs:(UTSSDKModulesDCloudUniPromptShowToastOptionsJSONObject * _Nonnull)options;
+ (void)s_hideToastByJs;
+ (void)s_showLoadingByJs:(UTSSDKModulesDCloudUniPromptShowLoadingOptionsJSONObject * _Nonnull)options;
+ (void)s_hideLoadingByJs;
+ (void)s_showModalByJs:(UTSSDKModulesDCloudUniPromptShowModalOptionsJSONObject * _Nonnull)options;
+ (void)s_showActionSheetByJs:(UTSSDKModulesDCloudUniPromptShowActionSheetOptionsJSONObject * _Nonnull)options;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UTSSDKModulesDCloudUniStorageIndexSwift")
@interface UTSSDKModulesDCloudUniStorageIndexSwift : NSObject
+ (void)s_setStorageByJs:(UTSSDKModulesDCloudUniStorageSetStorageOptionsJSONObject * _Nonnull)options;
+ (void)s_setStorageSyncByJs:(NSString * _Nonnull)key :(id _Nonnull)data;
+ (void)s_getStorageByJs:(UTSSDKModulesDCloudUniStorageGetStorageOptionsJSONObject * _Nonnull)options;
+ (id _Nullable)s_getStorageSyncByJs:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (void)s_getStorageInfoByJs:(UTSSDKModulesDCloudUniStorageGetStorageInfoOptionsJSONObject * _Nonnull)options;
+ (UTSSDKModulesDCloudUniStorageGetStorageInfoSuccess * _Nonnull)s_getStorageInfoSyncByJs SWIFT_WARN_UNUSED_RESULT;
+ (void)s_removeStorageByJs:(UTSSDKModulesDCloudUniStorageRemoveStorageOptionsJSONObject * _Nonnull)options;
+ (void)s_removeStorageSyncByJs:(NSString * _Nonnull)key;
+ (void)s_clearStorageByJs:(UTSSDKModulesDCloudUniStorageClearStorageOptionsJSONObject * _Nullable)option;
+ (void)s_clearStorageSyncByJs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UploadController")
@interface UTSSDKModulesDCloudUniNetworkUploadController : NSObject <NSURLSessionDataDelegate>
+ (UTSSDKModulesDCloudUniNetworkUploadController * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UploadFileOptionFiles")
@interface UTSSDKModulesDCloudUniNetworkUploadFileOptionFiles : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Null_unspecified uri;
@property (nonatomic) id _Nullable file;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end

@class UTSSDKModulesDCloudUniNetworkUploadFileSuccess;

SWIFT_CLASS_NAMED("UploadFileOptions")
@interface UTSSDKModulesDCloudUniNetworkUploadFileOptions : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified url;
@property (nonatomic, copy) NSString * _Nullable filePath;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSArray<UTSSDKModulesDCloudUniNetworkUploadFileOptionFiles *> * _Nullable files;
@property (nonatomic, strong) UTSJSONObject * _Nullable header;
@property (nonatomic, strong) UTSJSONObject * _Nullable formData;
@property (nonatomic, strong) NSNumber * _Nullable timeout;
@property (nonatomic, copy) void (^ _Nullable success)(UTSSDKModulesDCloudUniNetworkUploadFileSuccess * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable complete)(id _Nonnull);
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UploadFileOptionsJSONObject")
@interface UTSSDKModulesDCloudUniNetworkUploadFileOptionsJSONObject : NSObject <DCUniModel>
@property (nonatomic, copy) NSString * _Null_unspecified url;
@property (nonatomic, copy) NSString * _Nullable filePath;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSArray<UTSSDKModulesDCloudUniNetworkUploadFileOptionFiles *> * _Nullable files;
@property (nonatomic, strong) UTSJSONObject * _Nullable header;
@property (nonatomic, strong) UTSJSONObject * _Nullable formData;
@property (nonatomic, strong) NSNumber * _Nullable timeout;
@property (nonatomic, strong) UTSCallback * _Nullable success;
@property (nonatomic, strong) UTSCallback * _Nullable fail;
@property (nonatomic, strong) UTSCallback * _Nullable complete;
+ (NSDictionary<NSString *, id> * _Nullable)modelContainerPropertyGenericClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UploadFileSuccess")
@interface UTSSDKModulesDCloudUniNetworkUploadFileSuccess : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified data;
@property (nonatomic, strong) NSNumber * _Null_unspecified statusCode;
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(UTSJSONObject * _Nonnull)obj OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("UploadNetworkListener")
@interface UTSSDKModulesDCloudUniNetworkUploadNetworkListener : UTSSDKModulesDCloudUniNetworkNetworkUploadFileListener
@property (nonatomic, weak) id _Nullable task;
- (nonnull instancetype)init:(UTSSDKModulesDCloudUniNetworkUploadFileOptions * _Nonnull)param OBJC_DESIGNATED_INITIALIZER;
- (void)onProgress:(UTSSDKModulesDCloudUniNetworkOnProgressUpdateResult * _Nonnull)progressUpdate;
- (void)onDataReceived:(NSData * _Nonnull)data;
- (void)onFinished:(NSHTTPURLResponse * _Nonnull)response;
- (void)onFail:(NSError * _Nonnull)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UploadTaskByJsProxy")
@interface UTSSDKModulesDCloudUniNetworkUploadTaskByJsProxy : NSObject
- (void)abortByJs;
- (void)onProgressUpdateByJs:(UTSCallback * _Nonnull)callback;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
